#!/usr/bin/env python3
"""
Convert topic_explanation fields for questions 226-240 to markdown format.
"""

import re

# Read the file
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'r', encoding='utf-8') as f:
    content = f.read()

conversions = [
    # Q226
    (
        "A levator muscle raises or lifts a body part from its neutral anatomical position. The term comes from Latin 'levare' meaning 'to lift.' Examples include the levator scapulae (lifts shoulder blade) and levator ani (lifts pelvic floor). This is opposite to a depressor which lowers body parts. Levator action is distinct from flexion (bending at a joint) or tension (creating stiffness). Understanding muscle action terminology helps massage therapists communicate professionally about movement patterns and muscular dysfunction. Levator muscles are often overworked in clients who hold elevated postures.",
        "🎯 **Key Concept**: A levator muscle raises or lifts a body part from its neutral anatomical position. The term comes from Latin 'levare' meaning 'to lift.'\\n\\n💡 **Memory Tip**: LEVATOR = ELEVATOR - lifts things UP! (Like an elevator in a building)\\n\\n⚠️ **Exam Alert**: Examples include the levator scapulae (lifts shoulder blade) and levator ani (lifts pelvic floor). This is opposite to a depressor which lowers body parts. Levator action is distinct from flexion or tension.\\n\\n✅ **Why Correct**: Levator muscles are often overworked in clients who hold elevated postures. Understanding muscle action terminology helps massage therapists communicate professionally about movement patterns."
    ),
    # Q227
    (
        "Passive ROM must be performed slowly and rhythmically with continuous client communication about comfort levels. The therapist moves the client's joint through its range while the client remains completely relaxed. Quick, vigorous movements can cause injury, muscle guarding, or joint trauma. Slow movements allow proper assessment of restrictions, prevent overstretching, and maintain client safety. Ongoing communication ensures the client can report pain, discomfort, or concerns immediately. This technique is used to assess joint mobility, maintain flexibility, and prevent stiffness in clients who cannot actively move joints due to injury, surgery, or neurological conditions.",
        "🎯 **Key Concept**: Passive ROM must be performed slowly and rhythmically with continuous client communication about comfort levels.\\n\\n💡 **Memory Tip**: SLOW-MO with COMM-O - Slow Motion with Communication Only (never quick, always talk).\\n\\n⚠️ **Exam Alert**: Quick, vigorous movements can cause injury, muscle guarding, or joint trauma. Slow movements allow proper assessment of restrictions, prevent overstretching, and maintain client safety.\\n\\n✅ **Why Correct**: Ongoing communication ensures the client can report pain, discomfort, or concerns immediately. This technique is used to assess joint mobility and maintain flexibility in clients who cannot actively move joints."
    ),
    # Q228
    (
        "Professional ethics and infection control require therapists to prioritize client safety, especially with immunocompromised individuals who have weakened immune systems and increased susceptibility to infections. Any signs of illness (sore throat, fever, cold symptoms) indicate potential contagion risk. The therapist's duty of care mandates canceling appointments when ill, as even minor infections can cause serious complications in immune-suppressed clients. This protects both client health and maintains professional standards. Supplements like vitamin C don't eliminate transmission risk or justify treating clients while symptomatic.",
        "🎯 **Key Concept**: Professional ethics and infection control require therapists to prioritize client safety, especially with immunocompromised individuals who have weakened immune systems and increased susceptibility to infections.\\n\\n💡 **Memory Tip**: SICK? SKIP! When you're unwell, protect the vulnerable - Cancel and Care for your client's health first!\\n\\n⚠️ **Exam Alert**: Any signs of illness (sore throat, fever, cold symptoms) indicate potential contagion risk. Even minor infections can cause serious complications in immune-suppressed clients.\\n\\n✅ **Why Correct**: The therapist's duty of care mandates canceling appointments when ill. Supplements like vitamin C don't eliminate transmission risk or justify treating clients while symptomatic."
    ),
    # Q229
    (
        "NY State massage therapy advertising laws prohibit making guarantees about treatment outcomes or specific results like weight loss, as these constitute false or misleading claims that massage therapy cannot reliably deliver. Such guarantees violate professional standards and consumer protection laws. However, showing properly-draped clients in advertisements is not only permitted but demonstrates professionalism and adherence to modesty standards. Proper draping images show ethical practice and help educate the public about professional massage therapy standards, making this the only acceptable advertising feature among the options.",
        "🎯 **Key Concept**: NY State massage therapy advertising laws prohibit making guarantees about treatment outcomes or specific results like weight loss.\\n\\n💡 **Memory Tip**: NY Says NO to GUARANTEES! But YES to PROPER DRAPING - Show professionalism, not promises!\\n\\n⚠️ **Exam Alert**: Such guarantees constitute false or misleading claims that massage therapy cannot reliably deliver. They violate professional standards and consumer protection laws.\\n\\n✅ **Why Correct**: Showing properly-draped clients in advertisements is permitted and demonstrates professionalism and adherence to modesty standards, making this the only acceptable advertising feature."
    ),
    # Q230
    (
        "The hand receives primary innervation from the ulnar and median nerves, both arising from the brachial plexus. The median nerve innervates the lateral palm, thumb, index, middle, and lateral ring finger, controlling thenar muscles and providing sensation. The ulnar nerve innervates the medial hand, pinky, medial ring finger, and most intrinsic hand muscles including hypothenar muscles. Together, they enable fine motor control and sensation essential for hand function. The radial nerve also contributes to the dorsal hand but isn't listed in correct options. Understanding this innervation is crucial for identifying nerve compression syndromes and referral patterns.",
        "🎯 **Key Concept**: The hand receives primary innervation from the ulnar and median nerves, both arising from the brachial plexus.\\n\\n💡 **Memory Tip**: HUMAN hands need U&M: Ulnar and Median nerves! (Remember: U-M = yoU and Me use our hands!)\\n\\n⚠️ **Exam Alert**: The median nerve innervates the lateral palm, thumb, index, middle, and lateral ring finger. The ulnar nerve innervates the medial hand, pinky, medial ring finger, and most intrinsic hand muscles.\\n\\n✅ **Why Correct**: Together, they enable fine motor control and sensation essential for hand function. Understanding this innervation is crucial for identifying nerve compression syndromes and referral patterns."
    ),
    # Q231
    (
        "Postural drainage uses gravity positioning combined with specific massage techniques to mobilize and clear respiratory secretions. Vibration creates oscillating movements that help loosen thick mucus from bronchial walls, while tapotement (percussion) uses rhythmic striking motions like cupping and hacking to mechanically dislodge secretions and stimulate cough reflex. These techniques work synergistically - vibration loosens, tapotement mobilizes, and gravity assists drainage. This combination is essential for conditions like cystic fibrosis, pneumonia, or chronic bronchitis. Effleurage, while soothing, lacks the mechanical force needed to effectively mobilize thick secretions from respiratory passages.",
        "🎯 **Key Concept**: Postural drainage uses gravity positioning combined with specific massage techniques to mobilize and clear respiratory secretions.\\n\\n💡 **Memory Tip**: VIBRATE and TAP to TRAP the crap! (Vibration + Tapotement = Loosens mucus for drainage!)\\n\\n⚠️ **Exam Alert**: Vibration creates oscillating movements that loosen thick mucus from bronchial walls, while tapotement uses rhythmic striking motions to mechanically dislodge secretions and stimulate cough reflex.\\n\\n✅ **Why Correct**: These techniques work synergistically - vibration loosens, tapotement mobilizes, and gravity assists drainage. This combination is essential for conditions like cystic fibrosis, pneumonia, or chronic bronchitis."
    ),
    # Q232
    (
        "The parotid lymph nodes are strategically positioned anterior (in front of) the tragus of the ear, closely associated with the parotid salivary gland. These nodes drain lymphatic fluid from the temporal region, upper face, eyelids, and parts of the external ear. Their location makes them easily palpable during facial massage and lymphatic drainage work. When swollen, they may indicate infections or conditions affecting the scalp, face, or salivary glands. Understanding parotid node location is essential for therapists performing facial treatments, as gentle massage can support lymphatic drainage and reduce facial puffiness or congestion.",
        "🎯 **Key Concept**: The parotid lymph nodes are strategically positioned anterior (in front of) the tragus of the ear, closely associated with the parotid salivary gland.\\n\\n💡 **Memory Tip**: PAROTID by the ear's PART-OID! (Near the parotid gland, by the tragus part of your ear!)\\n\\n⚠️ **Exam Alert**: These nodes drain lymphatic fluid from the temporal region, upper face, eyelids, and parts of the external ear. Their location makes them easily palpable during facial massage and lymphatic drainage work.\\n\\n✅ **Why Correct**: When swollen, they may indicate infections or conditions affecting the scalp, face, or salivary glands. Understanding parotid node location is essential for therapists performing facial treatments."
    ),
    # Q233
    (
        "Decubitus ulcers (pressure sores) with purulent discharge indicate active infection and require immediate medical attention. These open wounds with foul-smelling pus suggest bacterial infection that could lead to sepsis if untreated. Massage is absolutely contraindicated as it could spread infection systemically or worsen tissue damage. The appropriate scope of practice response is immediate referral back to the physician without any massage treatment. This is a medical emergency, not a situation for consultation calls.",
        "🎯 **Key Concept**: Decubitus ulcers (pressure sores) with purulent discharge indicate active infection and require immediate medical attention.\\n\\n💡 **Memory Tip**: OOZING = OUT! When you see pus and smell, send them back to get well. Decubitus ulcers with discharge = immediate medical referral, no massage!\\n\\n⚠️ **Exam Alert**: These open wounds with foul-smelling pus suggest bacterial infection that could lead to sepsis if untreated. Massage is absolutely contraindicated as it could spread infection systemically or worsen tissue damage.\\n\\n✅ **Why Correct**: The appropriate scope of practice response is immediate referral back to the physician without any massage treatment. This is a medical emergency, not a situation for consultation calls."
    ),
    # Q234
    (
        "Friction is most indicated for lateral epicondylitis (tennis elbow) because it's a chronic tendinopathy involving adhesions and scar tissue formation. Deep transverse friction helps break down adhesions, realign collagen fibers, and promote healing in chronic tendon conditions. The lateral epicondyle area benefits from specific friction to address the chronic inflammatory changes and restore normal tissue function. This technique is contraindicated in acute conditions but excellent for chronic tendon problems.",
        "🎯 **Key Concept**: Friction is most indicated for lateral epicondylitis (tennis elbow) because it's a chronic tendinopathy involving adhesions and scar tissue formation.\\n\\n💡 **Memory Tip**: FRICTION for TENNIS elbow - Lateral Epicondylitis Loves Friction! Think 'Lateral = LATER I'll fix it with friction.' Chronic tendon issues need friction to break adhesions!\\n\\n⚠️ **Exam Alert**: Deep transverse friction helps break down adhesions, realign collagen fibers, and promote healing in chronic tendon conditions. The lateral epicondyle area benefits from specific friction.\\n\\n✅ **Why Correct**: This technique is contraindicated in acute conditions but excellent for chronic tendon problems like lateral epicondylitis."
    ),
    # Q235
    (
        "For chronically contracted muscles, friction to the tendon is most effective because chronic contractions create adhesions and restrictions at the tendon attachments (musculotendinous junctions). The tendon contains the proprioceptors and tension sensors that regulate muscle contraction. Deep friction at these attachment points helps break adhesions, reset proprioceptive feedback, and release chronic holding patterns. The belly of chronically contracted muscle is often too sensitive and reactive to respond well to direct friction work.",
        "🎯 **Key Concept**: For chronically contracted muscles, friction to the tendon is most effective because chronic contractions create adhesions and restrictions at the tendon attachments (musculotendinous junctions).\\n\\n💡 **Memory Tip**: CHRONIC Contract = TENDON Tract! 'When muscle won't let go, friction the tendon - that's where to go!' Chronic contractions need tendon friction to release the attachment points.\\n\\n⚠️ **Exam Alert**: The tendon contains the proprioceptors and tension sensors that regulate muscle contraction. Deep friction at these attachment points helps break adhesions and reset proprioceptive feedback.\\n\\n✅ **Why Correct**: The belly of chronically contracted muscle is often too sensitive and reactive to respond well to direct friction work. Tendon friction releases chronic holding patterns."
    ),
    # Q236
    (
        "The medial thigh contains three yin meridians: Kidney (KI), Spleen (SP), and Liver (LR). These meridians run along the inner leg from foot to torso, following the medial aspect of the lower extremity. In TCM theory, yin meridians relate to organ systems and run on the inner/medial surfaces of limbs, while yang meridians run on outer/lateral surfaces. The medial thigh specifically houses these three meridians as they ascend toward their respective organs in the trunk.",
        "🎯 **Key Concept**: The medial thigh contains three yin meridians: Kidney (KI), Spleen (SP), and Liver (LR).\\n\\n💡 **Memory Tip**: MEDIAL thigh = 'KiSs SPeaR LoveR' = KI, SP, LR! Inner thigh has the 'internal organ' meridians - Kidney, Spleen, Liver all run on the medial side!\\n\\n⚠️ **Exam Alert**: These meridians run along the inner leg from foot to torso. In TCM theory, yin meridians relate to organ systems and run on the inner/medial surfaces of limbs.\\n\\n✅ **Why Correct**: The medial thigh specifically houses these three meridians as they ascend toward their respective organs in the trunk. Yang meridians run on outer/lateral surfaces."
    ),
    # Q237
    (
        "The axillary nerve (C5-C6) innervates the deltoid and teres minor muscles. This nerve travels through the quadrangular space in the posterior shoulder and wraps around the surgical neck of the humerus. The deltoid provides shoulder abduction, while teres minor is one of the four rotator cuff muscles providing external rotation and stability. Axillary nerve injury commonly occurs with shoulder dislocations or humeral fractures, resulting in deltoid weakness and loss of shoulder abduction ability.",
        "🎯 **Key Concept**: The axillary nerve (C5-C6) innervates the deltoid and teres minor muscles.\\n\\n💡 **Memory Tip**: AXILLARY = 'Armpit eXits to DeLTa Teres' = Deltoid + Teres minor! The axillary nerve exits the armpit area to innervate the shoulder cap (deltoid) and small rotator (teres minor).\\n\\n⚠️ **Exam Alert**: This nerve travels through the quadrangular space in the posterior shoulder and wraps around the surgical neck of the humerus. The deltoid provides shoulder abduction, while teres minor is a rotator cuff muscle.\\n\\n✅ **Why Correct**: Axillary nerve injury commonly occurs with shoulder dislocations or humeral fractures, resulting in deltoid weakness and loss of shoulder abduction ability."
    ),
    # Q238
    (
        "NY State law requires massage therapists to provide client records upon request as part of professional conduct standards. This ensures transparency and client autonomy over their healthcare information. Personal activities like social drinking and mere criminal charges (without conviction) don't constitute professional misconduct. However, refusing to furnish records violates client rights and demonstrates unprofessional behavior that can result in disciplinary action including license suspension or revocation. Always maintain proper documentation and release records promptly when requested by clients.",
        "🎯 **Key Concept**: NY State law requires massage therapists to provide client records upon request as part of professional conduct standards.\\n\\n💡 **Memory Tip**: RECORD REFUSAL = REAL RISK! When clients cry 'Give me my files!' and you reply 'No!' - that's misconduct that makes lawyers smile!\\n\\n⚠️ **Exam Alert**: Refusing to furnish records violates client rights and demonstrates unprofessional behavior that can result in disciplinary action including license suspension or revocation.\\n\\n✅ **Why Correct**: This ensures transparency and client autonomy over their healthcare information. Personal activities like social drinking and mere criminal charges don't constitute professional misconduct."
    ),
    # Q239
    (
        "Tendonitis involves inflammation of tendons with formation of adhesions and scar tissue. The best treatment approach is friction massage applied to adhesions rather than the inflamed tendon directly. Frictioning adhesions helps break down fibrous restrictions, improves circulation, and restores normal tissue mobility. Direct friction on inflamed tendons can worsen inflammation. Complete avoidance provides no therapeutic benefit. Stripping away from tendons doesn't address the adhesions that limit function and cause pain.",
        "🎯 **Key Concept**: Tendonitis involves inflammation of tendons with formation of adhesions and scar tissue. The best treatment approach is friction massage applied to adhesions.\\n\\n💡 **Memory Tip**: ADHESIONS ARE THE ENEMY! Think 'Friction the Fibrosis' - target the sticky stuff (adhesions), not the inflamed tendon itself!\\n\\n⚠️ **Exam Alert**: Frictioning adhesions helps break down fibrous restrictions, improves circulation, and restores normal tissue mobility. Direct friction on inflamed tendons can worsen inflammation.\\n\\n✅ **Why Correct**: Complete avoidance provides no therapeutic benefit. Stripping away from tendons doesn't address the adhesions that limit function and cause pain."
    ),
    # Q240
    (
        "Frozen shoulder (adhesive capsulitis) involves severe restriction and pain in the glenohumeral joint with capsular adhesions. The best approach is working distal to the affected area for multiple sessions, focusing on surrounding musculature. This improves circulation, reduces compensatory tension, and prepares tissues before addressing the shoulder directly. Working the acute area initially can increase inflammation and pain. The surrounding muscles (neck, upper back, arm) develop compensatory patterns that need addressing first before direct shoulder work becomes appropriate.",
        "🎯 **Key Concept**: Frozen shoulder (adhesive capsulitis) involves severe restriction and pain in the glenohumeral joint with capsular adhesions.\\n\\n💡 **Memory Tip**: FROZEN = GO DISTANT! Think 'Distal Before Local' - work the neighborhood muscles first, then gradually move toward the frozen zone as things improve!\\n\\n⚠️ **Exam Alert**: The best approach is working distal to the affected area for multiple sessions, focusing on surrounding musculature. Working the acute area initially can increase inflammation and pain.\\n\\n✅ **Why Correct**: The surrounding muscles (neck, upper back, arm) develop compensatory patterns that need addressing first before direct shoulder work becomes appropriate."
    ),
]

# Apply conversions
for old_text, new_text in conversions:
    old_escaped = re.escape(old_text)
    content = re.sub(old_escaped, new_text, content)

# Write the file back
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Conversion complete for questions 226-240!")
