#!/usr/bin/env python3
"""
Convert topic_explanation fields for questions 241-287 to markdown format
"""

import re

# Define the conversions for each question ID
conversions = {
    241: '🎯 **Key Concept**: Fever and nausea are absolute contraindications for massage therapy. Fever signals active infection, and massage increases circulation which can spread pathogens throughout the body.\\n\\n💡 **Memory Tip**: "FEVER + NAUSEA = NO WAY!" When body temp spikes and stomach flips, massage trips must be skipped!\\n\\n⚠️ **Exam Alert**: Don\\'t fall for options suggesting light massage or shortened sessions - NO massage is appropriate regardless of duration or pressure when client has fever/nausea.\\n\\n✅ **Why Correct**: Professional standards and safety require refusing service during acute illness to protect both client health and prevent disease transmission.',

    242: '🎯 **Key Concept**: The tibial nerve is a major branch of the sciatic nerve that innervates posterior compartment muscles. The tibialis posterior muscle receives motor innervation from the tibial nerve.\\n\\n💡 **Memory Tip**: "TIBIAL goes to POSTERIOR!" - They\\'re both named tibial and both hang out in the back of the leg!\\n\\n⚠️ **Exam Alert**: Don\\'t confuse with tibialis anterior (deep peroneal nerve) or peroneus longus (superficial peroneal nerve).\\n\\n✅ **Why Correct**: Understanding nerve-muscle relationships is crucial for assessment and treatment of neurological conditions affecting movement patterns.',

    244: '🎯 **Key Concept**: In Traditional Chinese Medicine, the arm contains four major meridians: Heart and Small Intestine (Fire element), and Lung and Large Intestine (Metal element).\\n\\n💡 **Memory Tip**: "Fire + Metal = ARM-ed and dangerous!" Fire burns in heart/small intestine, Metal cuts like lungs/large intestine - both run through arms!\\n\\n⚠️ **Exam Alert**: Earth (spleen/stomach) and Water (kidney/bladder) elements run through legs, not arms. Wood (liver/gallbladder) runs through legs and sides.\\n\\n✅ **Why Correct**: Understanding meridian pathways helps massage therapists incorporate TCM principles and recognize referral patterns during treatment.',

    245: '🎯 **Key Concept**: The atlas is the first cervical vertebra (C1) that directly supports the skull. Unlike other vertebrae, it lacks a vertebral body and has a unique ring-shaped structure.\\n\\n💡 **Memory Tip**: "ATLAS holds up the WORLD (your head)!" Just like the Greek titan Atlas carried the world on his shoulders, C1 carries your head on your neck!\\n\\n⚠️ **Exam Alert**: Don\\'t confuse atlas with carpal bones (wrist bones) - atlas is C1 cervical vertebra at the top of your neck.\\n\\n✅ **Why Correct**: The atlanto-occipital joint is crucial for massage therapists working on neck tension, as it\\'s a common area of restriction and headache referral.',

    246: '🎯 **Key Concept**: Post-mastectomy lymphedema occurs when axillary (armpit) lymph nodes are surgically removed during cancer treatment, blocking normal lymphatic drainage from the arm.\\n\\n💡 **Memory Tip**: "LYMPH NODES REMOVED = DRAINAGE BLOCKED!" Think of lymph nodes as highway toll booths - remove the booths and traffic backs up!\\n\\n⚠️ **Exam Alert**: This is a serious contraindication for deep massage on the affected limb. Always obtain physician clearance before treating.\\n\\n✅ **Why Correct**: Without axillary lymph nodes, lymphatic fluid accumulates causing swelling in the arm, hand, and sometimes chest wall on the affected side.',

    247: '🎯 **Key Concept**: Vibration massage involves rapid oscillating movements where the primary force comes from contraction and relaxation of forearm muscles (flexors and extensors).\\n\\n💡 **Memory Tip**: "VIBRATE with your FOREARMS, not your fingers!" Think of guitar strings vibrating from the neck (forearm), not the tuning pegs (fingers).\\n\\n⚠️ **Exam Alert**: Using fingers alone causes fatigue and lacks power. Legs provide no mechanical advantage for hand techniques.\\n\\n✅ **Why Correct**: Proper vibration technique protects therapists from repetitive strain injury and delivers therapeutic benefits including muscle relaxation and increased circulation.',

    248: '🎯 **Key Concept**: New York State defines massage therapy as manual manipulation of soft tissue for therapeutic purposes. Rolfing (Structural Integration) involves hands-on manipulation of fascia and connective tissue, fitting this definition.\\n\\n💡 **Memory Tip**: "ROLFING ROLLS into massage therapy!" Massage therapists roll and manipulate soft tissue, just like Rolfing manipulates fascia.\\n\\n⚠️ **Exam Alert**: Reiki (energy work), homeopathy (oral remedies), and chiropractic (joint manipulation) fall outside massage therapy scope in New York.\\n\\n✅ **Why Correct**: Rolfing requires the same anatomical knowledge and manual skills as traditional massage, making it a recognized form of massage therapy in NY.',

    249: '🎯 **Key Concept**: Massage therapy produces physiological effects remarkably similar to regular exercise - both increase circulation, enhance lymphatic drainage, improve muscle flexibility, reduce stress hormones, and promote endorphin release.\\n\\n💡 **Memory Tip**: "Massage Makes Exercise Easier!" Both boost circulation, muscle tone, and overall wellness without the sweat!\\n\\n⚠️ **Exam Alert**: This makes massage an excellent therapeutic substitute for patients unable to exercise due to injury, illness, or physical limitations.\\n\\n✅ **Why Correct**: Exercise creates benefits through active muscle contraction; massage achieves similar outcomes through manual manipulation of soft tissues.',

    250: '🎯 **Key Concept**: Pre-event tapotement serves specific neuromuscular preparation functions - the rapid percussive strokes stimulate motor nerves and trigger reflexive muscle contractions that prime the system for athletic activity.\\n\\n💡 **Memory Tip**: "Tap Contracts and Sparks!" Tapotement makes muscles contract and nerves spark before competition!\\n\\n⚠️ **Exam Alert**: While tapotement does increase circulation, the PRIMARY pre-event goals are neurological activation and muscular priming, not vascular effects.\\n\\n✅ **Why Correct**: This nerve stimulation enhances proprioception and muscle readiness, preparing the neuromuscular system for sustained athletic demands.',

    251: '🎯 **Key Concept**: Neuralgia involves inflamed or irritated nerves causing sharp, burning pain. Clients often cannot tolerate continuous contact techniques like effleurage or sustained vibration.\\n\\n💡 **Memory Tip**: "Nerve pain needs Gentle Tapping!" When nerves are angry, light tapping soothes while sliding strokes aggravate!\\n\\n⚠️ **Exam Alert**: Nerve tapping (gentle, rhythmic tapotement) provides therapeutic benefit without prolonged contact that might exacerbate nerve irritation.\\n\\n✅ **Why Correct**: Brief, intermittent contact allows therapeutic stimulation while giving hypersensitive nerves recovery time between contacts.',

    252: '🎯 **Key Concept**: Proprioception is the body\\'s sixth sense - the ability to perceive body position, movement, and spatial orientation without visual input through specialized receptors in muscles, tendons, joints, and inner ear.\\n\\n💡 **Memory Tip**: "ProPrio = Pro Position!" Your body\\'s internal GPS that knows where you are without looking!\\n\\n⚠️ **Exam Alert**: This is what allows you to touch your nose with eyes closed or walk without constantly looking at your feet.\\n\\n✅ **Why Correct**: Massage therapy can enhance proprioceptive awareness by stimulating these receptors through joint mobilization and deep tissue work.',

    253: '🎯 **Key Concept**: CV-6 (Conception Vessel 6), also called Qihai, translates literally as "Sea of Qi" in Traditional Chinese Medicine. Located 1.5 inches below the navel, it\\'s the body\\'s primary reservoir of vital energy.\\n\\n💡 **Memory Tip**: "CV-6 is the Sea!" Conception Vessel 6 holds the ocean of life energy below the belly!\\n\\n⚠️ **Exam Alert**: This point is frequently used in acupuncture and acupressure treatments for fatigue, digestive disorders, and general wellness enhancement.\\n\\n✅ **Why Correct**: CV-6 is considered the center of original qi (yuan qi) and serves as the foundation for all energy circulation throughout the meridian system.',

    254: '🎯 **Key Concept**: The Lung (LU) meridian contains exactly 11 acupoints running from the lateral chest (LU-1 Zhongfu) to the thumb (LU-11 Shaoshang) along the arm\\'s radial side.\\n\\n💡 **Memory Tip**: "LU-nch at ELEVEN!" The Lung meridian has 11 points, just like taking an 11 o\\'clock lunch break to breathe fresh air!\\n\\n⚠️ **Exam Alert**: This is one of the shorter meridians compared to Bladder (67 points) or Stomach (45 points).\\n\\n✅ **Why Correct**: This meridian is crucial in TCM for respiratory function, immune system support, and skin health.',

    255: '🎯 **Key Concept**: The Autonomic Nervous System (ANS) controls involuntary functions essential for survival. Eye movements include both voluntary and involuntary components - the ANS specifically controls pupillary responses, tear production, and protective blinking reflexes.\\n\\n💡 **Memory Tip**: "EYE Can\\'t Control It!" Eye movements (blinking, pupil dilation) are autonomic, while fingers need conscious control!\\n\\n⚠️ **Exam Alert**: While pupil dilation alone is autonomic, the complete eye system involves more comprehensive autonomic regulation including multiple protective mechanisms.\\n\\n✅ **Why Correct**: Finger movements are controlled by the somatic nervous system requiring conscious motor cortex activation, not autonomic regulation.',

    256: '🎯 **Key Concept**: Radial deviation is the lateral movement of the wrist toward the thumb side (radial side) when the body is in anatomical position, occurring primarily at the radiocarpal and midcarpal joints.\\n\\n💡 **Memory Tip**: "RADIAL = RADIUS bone = THUMB side!" When you deviate toward your radius bone, you\\'re doing RADIAL deviation!\\n\\n⚠️ **Exam Alert**: Normal radial deviation range is approximately 15-20 degrees, while ulnar deviation allows 30-35 degrees.\\n\\n✅ **Why Correct**: The radius bone\\'s position on the thumb side provides the anatomical reference - \\'radial\\' always refers to the thumb side, while \\'ulnar\\' refers to the pinky side.',

    257: '🎯 **Key Concept**: The Lung and Triple Energizer (San Jiao) meridians are fundamental in Traditional Chinese Medicine for treating immunodeficiency disorders. The Lung governs respiratory function and defensive Qi, while Triple Energizer regulates body cavities and fluid transformation.\\n\\n💡 **Memory Tip**: "LUNG Triple Threat!" LUngs filter air, Triple Energizer regulates immunity - together they\\'re your immune system\\'s dynamic duo!\\n\\n⚠️ **Exam Alert**: These meridians are frequently targeted in treatments for chronic fatigue, recurrent infections, and autoimmune conditions.\\n\\n✅ **Why Correct**: Together, they manage the body\\'s protective mechanisms, respiratory immunity, and overall defensive capabilities essential for immune function.',

    258: '🎯 **Key Concept**: Myelinated nerve fibers conduct impulses via saltatory conduction, where electrical signals \\'jump\\' from one Node of Ranvier to the next, rather than traveling continuously along the entire axon membrane.\\n\\n💡 **Memory Tip**: "SALTATORY = SALT jumping!" Like a grasshopper hopping from lily pad to lily pad - myelinated nerves jump from node to node!\\n\\n⚠️ **Exam Alert**: Saltatory conduction is significantly faster (up to 100x) and more energy-efficient than continuous conduction in unmyelinated fibers.\\n\\n✅ **Why Correct**: This jumping mechanism allows rapid transmission of sensory and motor information essential for quick reflexes and coordinated movement.',

    259: '🎯 **Key Concept**: A motor unit is the fundamental functional unit of muscle contraction, consisting of one alpha motor neuron and all the muscle fibers it innervates. When the motor neuron fires, ALL fibers in that unit contract simultaneously.\\n\\n💡 **Memory Tip**: "Motor Unit = My Unit!" One nerve boss controlling its team of muscle workers!\\n\\n⚠️ **Exam Alert**: Small motor units (3-5 fibers) provide fine control for eye muscles, while large motor units (1000+ fibers) generate power in gastrocnemius.\\n\\n✅ **Why Correct**: Motor unit recruitment follows the size principle: smaller units recruit first for precise movements, larger units recruit for forceful contractions.',

    260: '🎯 **Key Concept**: Humeral adduction brings the arm toward the body\\'s midline. The primary adductors are the pectoralis major (anterior muscle) and latissimus dorsi (posterior muscle), both inserting on the humerus.\\n\\n💡 **Memory Tip**: "PecS and LatS ATTRACT the arm! PLAT = Pec major + Lats Adduct Toward body!" Think of hugging yourself - Pecs in front, Lats from behind!\\n\\n⚠️ **Exam Alert**: Pec major also provides horizontal adduction (hugging motion), while lats provide extension and internal rotation.\\n\\n✅ **Why Correct**: These muscles are crucial for climbing, swimming, and pulling movements toward the body, creating powerful adduction when contracting together.',

    261: '🎯 **Key Concept**: Flaccid muscle (hypotonia) results from lower motor neuron damage, specifically anterior horn cells in the spinal cord. When damaged, muscles lose all voluntary control and reflexes.\\n\\n💡 **Memory Tip**: "FLACCID = Floppy!" Anterior horn damage = floppy muscles, like unplugging an electrical device!\\n\\n⚠️ **Exam Alert**: This differs from upper motor neuron lesions which cause spastic paralysis with hyperreflexia. Flaccid muscles show absent reflexes, atrophy, and fasciculations.\\n\\n✅ **Why Correct**: Anterior horn cell damage occurs in polio, ALS, and spinal cord injuries. The muscle becomes floppy because it receives no neural stimulation.',

    262: '🎯 **Key Concept**: Ankylosing Spondylitis (AS) is a chronic inflammatory arthritis primarily affecting the vertebral column and sacroiliac joints, causing progressive fusion of spinal segments creating a characteristic \\'bamboo spine\\' appearance.\\n\\n💡 **Memory Tip**: "ANKYLOSING = spine LINKING together! SPONDYL = spine!" Think ankle-osing but it\\'s the spine joints that get stiff!\\n\\n⚠️ **Exam Alert**: The condition typically begins in the sacroiliac joints and ascends the spine. Early signs include lower back pain, morning stiffness, and reduced spinal flexibility.\\n\\n✅ **Why Correct**: AS predominantly affects young males and has strong genetic associations with HLA-B27. Inflammation leads to ossification of ligaments and eventual ankylosis.',

    263: '🎯 **Key Concept**: The rectus femoris originates at the Anterior Inferior Iliac Spine (AIIS), making it unique among the quadriceps as the only bi-articular muscle (crosses both hip and knee joints).\\n\\n💡 **Memory Tip**: "Rectus Femoris = RF = Really Front! It needs AIIS = A Really Important Iliac Spot!"\\n\\n⚠️ **Exam Alert**: Unlike the other three quadriceps muscles that only cross the knee, rectus femoris assists in hip flexion due to its AIIS origin.\\n\\n✅ **Why Correct**: This dual function allows rectus femoris to flex the hip while extending the knee - crucial for kicking motions. The muscle runs straight down the anterior thigh.',

    264: '🎯 **Key Concept**: In Traditional Chinese Medicine\\'s five-element theory, Fire element governs the heart, circulation, and sweat production. When body temperature rises (fire/heat), we sweat to cool down.\\n\\n💡 **Memory Tip**: "Fire makes you SWEAT!" Think of sitting by a hot campfire and perspiring. Fire = Heat = Sweat!\\n\\n⚠️ **Exam Alert**: Other elements have their own secretions: Water (urine), Wood (tears), Earth (saliva), Metal (mucus).\\n\\n✅ **Why Correct**: The fire element also relates to emotions like joy and excitement, which can trigger sweating. Understanding these correspondences helps incorporate TCM principles.',

    265: '🎯 **Key Concept**: The sternum (breastbone) consists of three fused parts: manubrium (top), gladiolus/body (middle), and xyphoid process (bottom tip). The styloid process is NOT part of the sternum.\\n\\n💡 **Memory Tip**: "Sternum has 3 parts: Man-GLad-Xy (Manubrium, Gladiolus, Xyphoid). STYLOID is STYLED differently - it\\'s found elsewhere!"\\n\\n⚠️ **Exam Alert**: The styloid process is a pointed projection found on the temporal bone of the skull and the radius/ulna bones of the forearm, not the sternum.\\n\\n✅ **Why Correct**: This distinction is crucial for accurate anatomical palpation during massage therapy. The sternum\\'s three parts are all located in the chest.',

    266: '🎯 **Key Concept**: The lumbosacral plexus gives rise to nerves that innervate the lower extremities. The three major nerves are: Femoral nerve (L2-L4) for quadriceps, Obturator nerve (L2-L4) for adductors, and Sciatic nerve (L4-S3) for posterior thigh.\\n\\n💡 **Memory Tip**: "FOScial media!" Femoral, Obturator, Sciatic are the three big nerves that keep your legs \\'socially active\\'!\\n\\n⚠️ **Exam Alert**: These nerves can be affected by piriformis syndrome, hip dysfunction, or lumbar spine issues.\\n\\n✅ **Why Correct**: Understanding these pathways helps massage therapists with assessment and treatment planning for neurological conditions affecting lower extremity function.',

    267: '🎯 **Key Concept**: Fibrosis and contracture develop when there\\'s prolonged muscle imbalance between antagonistic muscle groups. When one muscle group is consistently overactive, it develops excessive fibrous connective tissue and shortened length.\\n\\n💡 **Memory Tip**: "Muscle imbalance = Fibrosis Formation!" Like a rope that\\'s always pulled from one side - it gets tight and fibrous!\\n\\n⚠️ **Exam Alert**: Common examples include tight hip flexors with weak glutes, or tight chest muscles with weak rhomboids.\\n\\n✅ **Why Correct**: Massage therapy helps break this cycle by releasing tight tissues and facilitating proper muscle balance restoration through targeted techniques.',

    268: '🎯 **Key Concept**: When working with minors (under 18), massage therapists must obtain written parental consent before communicating with any healthcare providers about the child\\'s condition.\\n\\n💡 **Memory Tip**: "Minor Medical info = Mom/dad Must know first!" Always get parental permission before discussing minor\\'s conditions with healthcare providers.\\n\\n⚠️ **Exam Alert**: This protects the minor\\'s rights while ensuring proper communication channels. Never bypass parents/guardians when dealing with minor clients\\' medical information.\\n\\n✅ **Why Correct**: This approach maintains professional boundaries, follows legal requirements for minors, and ensures safe, informed care for the 14-year-old client.',

    269: '🎯 **Key Concept**: In massage therapy practice, breast massage is primarily performed on female clients for therapeutic purposes. NY State law requires informed consent specifically from female clients before undraping for breast massage.\\n\\n💡 **Memory Tip**: "FEMALE FIRST!" Only Female clients need Full consent For breast work (males don\\'t typically receive breast massage in standard practice).\\n\\n⚠️ **Exam Alert**: This protects both client and therapist by ensuring clear communication, boundaries, and legal protection due to the sensitive nature of this area.\\n\\n✅ **Why Correct**: Male clients typically don\\'t receive breast tissue massage as part of standard therapeutic practice, though pectoral muscle work may be performed with appropriate draping.',

    270: '🎯 **Key Concept**: When massaging the anterior leg, proper body mechanics and client comfort require the knee to be supported with a bolster, pillow, or towel roll placed underneath.\\n\\n💡 **Memory Tip**: "SUPPORT THE SPOT!" Always Support the knee, don\\'t let it hang or bend awkwardly during anterior leg work.\\n\\n⚠️ **Exam Alert**: Supporting the knee prevents hyperextension, reduces strain on the joint, maintains proper alignment, and allows the leg muscles to relax fully.\\n\\n✅ **Why Correct**: The support should maintain a slight natural bend in the knee while keeping the leg stable during massage techniques. Unsupported positioning causes discomfort and muscle tension.',

    271: '🎯 **Key Concept**: When performing palmar kneading on the posterior thigh in prone position, the knee should be slightly flexed (approximately 15-30 degrees) to optimize muscle accessibility and technique effectiveness.\\n\\n💡 **Memory Tip**: "SLIGHT SIGHT!" Slightly flexed knee gives you better Sight and access to posterior thigh muscles for effective kneading.\\n\\n⚠️ **Exam Alert**: This positioning allows the hamstring muscles to relax and become more pliable, making kneading more effective.\\n\\n✅ **Why Correct**: A slight flex prevents muscles from being stretched taut against the table. The flexion can be achieved with a small bolster or towel roll under the ankle/lower leg.',

    272: '🎯 **Key Concept**: New York State allows temporary massage therapy licenses for up to 12 months maximum. This provides newly graduated therapists time to complete remaining requirements and transition to full licensing.\\n\\n💡 **Memory Tip**: "TEMP for TWELVE!" Temporary license lasts up to Twelve months maximum in NY.\\n\\n⚠️ **Exam Alert**: The 12-month limit ensures practitioners cannot indefinitely practice on temporary status and must complete full licensing requirements within a reasonable timeframe.\\n\\n✅ **Why Correct**: This protects public safety by ensuring all practicing therapists meet complete state standards while allowing flexibility for legitimate transition periods.',

    273: '🎯 **Key Concept**: Lymphatic plexuses are networks of lymphatic vessels found throughout most body tissues. However, the brain lacks traditional lymphatic plexuses - it uses the cerebrospinal fluid system and glymphatic system instead.\\n\\n💡 **Memory Tip**: "NO BRAIN DRAIN!" The Brain has No lymphatic plexuses, it uses cerebrospinal fluid Drainage instead!\\n\\n⚠️ **Exam Alert**: Lymphatic plexuses exist in hands, feet, breasts, and most peripheral tissues for draining interstitial fluid and transporting lymph.\\n\\n✅ **Why Correct**: The blood-brain barrier and specialized CSF circulation handle fluid balance and waste removal in neural tissue, making conventional lymphatic drainage unnecessary.',

    274: '🎯 **Key Concept**: Proper draping serves three primary functions: maintaining client comfort by reducing anxiety, providing warmth to prevent muscle tension, and preserving modesty/privacy. Physical support comes from bolsters and the table, NOT draping.\\n\\n💡 **Memory Tip**: "Draping is for CWM (Comfort, Warmth, Modesty) - but NOT for Support!" Support comes from the table, not the sheet!\\n\\n⚠️ **Exam Alert**: Understanding draping purposes is crucial for maintaining professional boundaries and creating a safe therapeutic environment.\\n\\n✅ **Why Correct**: Draping involves strategic placement of sheets/towels to expose only the area being worked on. It\\'s both an ethical obligation and legal requirement.',

    275: '🎯 **Key Concept**: The Serratus Anterior is a fan-shaped muscle that originates on ribs 1-8 and inserts on the medial border of the scapula. Its primary action is scapular abduction (protraction), pulling the shoulder blade away from the spine.\\n\\n💡 **Memory Tip**: "Serratus = SAW tooth ABduction!" Picture a SAW cutting AWAY from the body (ABduction). The muscle looks like saw teeth!\\n\\n⚠️ **Exam Alert**: This muscle is called the \\'boxer\\'s muscle\\' because it\\'s essential for punching motions. Weakness causes \\'winged scapula\\'.\\n\\n✅ **Why Correct**: The muscle is crucial for pushing movements and overhead arm motions. Adduction/retraction would be performed by rhomboids and middle trapezius.',

    276: '🎯 **Key Concept**: The Bladder meridian (BL) is the longest meridian in TCM, running from the inner eye down the back and leg to end at BL-67 on the lateral side of the little toe at the nail bed corner.\\n\\n💡 **Memory Tip**: "BL-67 is where the Bladder LEAKS out - at the Little toe! Bladder empties at the END (67 is the last point) on the lateral pinky toe!"\\n\\n⚠️ **Exam Alert**: BL-67 is significant in acupuncture and is often used to turn breech babies and treat headaches.\\n\\n✅ **Why Correct**: Understanding meridian endpoints is crucial for energy work and acupressure techniques. The bladder meridian contains 67 points total, making BL-67 the final point.',

    277: '🎯 **Key Concept**: The Large Intestine meridian (LI) begins at LI-1, located on the radial side of the index finger at the corner of the nail bed. This meridian deals with elimination and letting go, both physically and emotionally.\\n\\n💡 **Memory Tip**: "Large Intestine starts where you POINT to eliminate waste - at the INDEX finger! LI-1 is on the Radial side (thumb side)!"\\n\\n⚠️ **Exam Alert**: The large intestine meridian runs from the index finger up the arm, across the shoulder, up the neck to end at the nostril (LI-20).\\n\\n✅ **Why Correct**: Understanding meridian starting points is essential for energy work and directional flow in therapeutic massage.',

    278: '🎯 **Key Concept**: The Small Intestine meridian is associated with the separation of pure from impure substances in TCM. It begins at SI-1 on the ulnar side (pinky side) of the little finger.\\n\\n💡 **Memory Tip**: "Small Intestine SORTS pure from impure - starts on the Small side (ulnar) of the little finger! SI separates nutrients from waste!"\\n\\n⚠️ **Exam Alert**: The SI meridian runs up the arm, across the scapula, up the neck to end near the ear. It governs mental clarity and decision-making.\\n\\n✅ **Why Correct**: In TCM, the small intestine is called the \\'Separator of Pure and Impure\\' - both physically (nutrient absorption) and mentally (clear thinking vs confusion).',

    279: '🎯 **Key Concept**: In New York State, Shiatsu is considered a form of massage therapy and falls under the state\\'s massage licensing requirements. Practitioners must obtain a NY State massage therapy license to legally practice any massage modality.\\n\\n💡 **Memory Tip**: "NY Says: Same License, Same State!" All massage modalities including Shiatsu need the same NY massage license!\\n\\n⚠️ **Exam Alert**: The state doesn\\'t recognize separate Shiatsu certifications as sufficient for independent practice. This unified licensing approach protects consumers.\\n\\n✅ **Why Correct**: This ensures practitioners meet standardized education, examination, and safety requirements across all massage modalities, maintaining professional standards.',

    280: '🎯 **Key Concept**: The piriformis muscle, located deep in the buttock region, is unique in performing both lateral rotation and abduction of the hip. It originates from the anterior sacrum and inserts on the greater trochanter.\\n\\n💡 **Memory Tip**: "Piriformis is a PEAR-shaped muscle that PAIRS lateral rotation with abduction - it does both!"\\n\\n⚠️ **Exam Alert**: The piriformis can become problematic when tight, potentially compressing the sciatic nerve (piriformis syndrome), causing pain and numbness down the leg.\\n\\n✅ **Why Correct**: This dual action makes it crucial for hip stability and movement. When contracted, it rotates the thigh outward and moves it away from the midline.',

    281: '🎯 **Key Concept**: Spasticity is a common post-stroke condition characterized by involuntary muscle contractions and increased muscle tone. The inverted foot position is typical of spastic patterns in stroke survivors.\\n\\n💡 **Memory Tip**: "Spastic = STUCK!" Muscles are STuck in Uncontrolled Contraction after stroke, creating the characteristic equinovarus foot position!\\n\\n⚠️ **Exam Alert**: Spasticity differs from voluntary muscle contraction as it\\'s involuntary, persistent, and often painful, significantly impacting mobility.\\n\\n✅ **Why Correct**: In hemiplegia, affected muscles develop spasticity as the brain\\'s inhibitory control is damaged, keeping certain muscle groups contracted.',

    282: '🎯 **Key Concept**: Bronchiectasis involves damaged, widened airways that accumulate thick secretions. Postural drainage positions the affected lung segments above the mouth, using gravity to help mobilize secretions.\\n\\n💡 **Memory Tip**: "Bronchiectasis = DRAIN the TRAIN!" Position head DOWN like a train going downhill to drain secretions!\\n\\n⚠️ **Exam Alert**: The prone position with head lower than chest (Trendelenburg-like positioning) allows gravity to assist in moving secretions toward larger airways.\\n\\n✅ **Why Correct**: This positioning, combined with percussion and vibration techniques, helps clear airways and prevent infection complications.',

    283: '🎯 **Key Concept**: The tibialis anterior muscle is the primary dorsiflexor of the foot and also assists with inversion. Located on the anterior lower leg, it originates from the lateral tibia and inserts on the medial cuneiform.\\n\\n💡 **Memory Tip**: "Tibialis Anterior = TAXI!" It Takes you ANteriorly (dorsiflexion) and Inward (inversion)!\\n\\n⚠️ **Exam Alert**: In cycling, this muscle activates during the upstroke of the pedal cycle, lifting the foot and preparing for the next downward power stroke.\\n\\n✅ **Why Correct**: When contracted, it pulls the foot upward (dorsiflexion) and slightly inward (inversion). This dual action makes it easily identifiable.',

    284: '🎯 **Key Concept**: Tapotement is a percussion-based massage technique category involving rhythmic striking movements. The main techniques include clapping (cupped hands), drumming (fingertips), pounding (loose fists), hacking (edge of hands), and beating (flat palms).\\n\\n💡 **Memory Tip**: "TAP dancers CLAP while they perform!" Tapotement includes Clapping, Along with Pounding!\\n\\n⚠️ **Exam Alert**: These techniques stimulate circulation, invigorate muscles, and energize the nervous system. Perform with relaxed hands and wrists for bouncing effect.\\n\\n✅ **Why Correct**: Tapotement is typically used toward the end of massage sessions to stimulate and awaken the client after relaxation work.',

    285: '🎯 **Key Concept**: Hemophilia is a hereditary bleeding disorder caused by deficiencies in specific clotting factors (Factor VIII in Hemophilia A, Factor IX in Hemophilia B), preventing proper clot formation.\\n\\n💡 **Memory Tip**: "HEMOphilia affects HEMO (blood)!" Can\\'t CLOT properly, blood won\\'t STOP!\\n\\n⚠️ **Exam Alert**: This condition is typically contraindicated for massage due to risk of internal bleeding from tissue manipulation. Even light pressure can cause hematomas or joint bleeding.\\n\\n✅ **Why Correct**: The blood coagulation cascade is disrupted, resulting in prolonged bleeding after injuries and spontaneous bleeding into joints and muscles.',

    286: '🎯 **Key Concept**: Venostasis refers to sluggish venous circulation where blood pools in lower extremities. Without obstruction, massage strokes should move from distal to proximal (toward the heart) to encourage fluid movement.\\n\\n💡 **Memory Tip**: "Venus STASIS needs help going UP!" Massage TOWARD the heart, PROXIMAL direction UP!\\n\\n⚠️ **Exam Alert**: Work begins distal to the affected area and moves proximally, following natural drainage patterns. Use light to moderate pressure, avoiding deep pressure.\\n\\n✅ **Why Correct**: This helps reduce swelling and improve circulation by assisting venous and lymphatic return toward the heart, following natural drainage patterns.',

    287: '🎯 **Key Concept**: In Traditional Chinese Medicine, Yang meridians flow downward in anatomical position, representing descending energy from heaven to earth. Yang energy is associated with activity, heat, and outward movement.\\n\\n💡 **Memory Tip**: "YANG is like the SUN going DOWN!" Yang meridians flow DOWNWARD from heaven to earth!\\n\\n⚠️ **Exam Alert**: The six Yang meridians (Large Intestine, Triple Heater, Small Intestine, Stomach, Gallbladder, Bladder) flow from head/upper body downward toward hands and feet.\\n\\n✅ **Why Correct**: This contrasts with Yin meridians, which flow upward from earth to heaven. Understanding flow direction is crucial for acupressure techniques and energy work.',
}

def main():
    # Read the file
    file_path = r'C:\git\nysmassageexam.com\data\questions.ts'

    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Process each question
    for question_id, new_explanation in conversions.items():
        # Find the question block using id
        pattern = rf'(\{{\s*"id":\s*{question_id},.*?"topic_explanation":\s*")([^"]*(?:\\.[^"]*)*)(")'

        def replace_explanation(match):
            return match.group(1) + new_explanation + match.group(3)

        content = re.sub(pattern, replace_explanation, content, flags=re.DOTALL)
        print(f"Processed question {question_id}")

    # Write the updated content back
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"\nSuccessfully converted topic_explanations for questions 241-287!")

if __name__ == '__main__':
    main()
