#!/usr/bin/env python3
"""
Convert topic_explanation fields for questions 211-225 to markdown format.
"""

import re

# Read the file
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'r', encoding='utf-8') as f:
    content = f.read()

conversions = [
    # Q211
    (
        "Knotting sensations indicate trigger points - hyperirritable spots within taut muscle bands that refer pain and cause dysfunction. Trigger points develop from muscle overuse, stress, poor posture, creating localized ischemia and metabolic dysfunction. The upper traps and thoracic region are common trigger point locations due to postural strain. Trigger point therapy uses sustained pressure to deactivate these points, restore circulation, and release muscle tension. This technique specifically targets the pathophysiology of trigger points, unlike general techniques that don't address the specific neurological and metabolic dysfunction occurring in these areas.",
        "🎯 **Key Concept**: Knotting sensations indicate trigger points - hyperirritable spots within taut muscle bands that refer pain and cause dysfunction.\\n\\n💡 **Memory Tip**: KNOTS need TRIGGER point therapy - when client says 'KNOTS', think TRIGGER SPOTS! TRIGger point therapy TRIGgers relief!\\n\\n⚠️ **Exam Alert**: Trigger points develop from muscle overuse, stress, poor posture, creating localized ischemia and metabolic dysfunction. The upper traps and thoracic region are common locations due to postural strain.\\n\\n✅ **Why Correct**: Trigger point therapy uses sustained pressure to deactivate these points, restore circulation, and release muscle tension - specifically targeting the neurological and metabolic dysfunction."
    ),
    # Q212
    (
        "The Linea Alba is the fibrous structure running down the center of the abdomen, often involved in surgical incisions. One week post-surgery, tissues are in acute healing phase with inflammation, fragile scar formation, and compromised circulation. Deep friction could disrupt healing tissue, cause pain, or damage delicate repair processes. Gentle relaxation massage promotes parasympathetic healing response, while proximal lymphatic drainage (working toward the heart from areas above the surgical site) helps reduce swelling without disturbing the surgical area directly. This approach supports natural healing while avoiding mechanical stress on vulnerable tissues.",
        "🎯 **Key Concept**: One week post-surgery, tissues are in acute healing phase with inflammation, fragile scar formation, and compromised circulation.\\n\\n💡 **Memory Tip**: Post-Surgery = PEACE: Proximal first, Easy touch, Avoid friction, Circulation gently, Emergency healing mode.\\n\\n⚠️ **Exam Alert**: The Linea Alba is the fibrous structure running down the center of the abdomen, often involved in surgical incisions. Deep friction could disrupt healing tissue, cause pain, or damage delicate repair processes.\\n\\n✅ **Why Correct**: Gentle relaxation massage promotes parasympathetic healing response, while proximal lymphatic drainage helps reduce swelling without disturbing the surgical area directly."
    ),
    # Q213
    (
        "Connective tissue is the most abundant tissue type, making up roughly 45% of body weight. It includes diverse structures: bones, cartilage, tendons, ligaments, fascia, blood, lymph, and adipose tissue. Its primary function is structural support, protection, and connection between other tissue types. The extracellular matrix (collagen, elastin, ground substance) gives connective tissue its strength and flexibility. This abundance makes sense anatomically - every organ, muscle, and structure needs connective tissue framework for support, blood supply, and structural integrity. Understanding this helps therapists appreciate how massage affects the body's primary structural system.",
        "🎯 **Key Concept**: Connective tissue is the most abundant tissue type, making up roughly 45% of body weight.\\n\\n💡 **Memory Tip**: Connective tissue CONNECTS everything - tendons, ligaments, bones, cartilage, blood, fat - it's EVERYWHERE supporting all other tissues!\\n\\n⚠️ **Exam Alert**: It includes diverse structures: bones, cartilage, tendons, ligaments, fascia, blood, lymph, and adipose tissue. Its primary function is structural support, protection, and connection between other tissue types.\\n\\n✅ **Why Correct**: Every organ, muscle, and structure needs connective tissue framework for support, blood supply, and structural integrity. Understanding this helps therapists appreciate how massage affects the body's primary structural system."
    ),
    # Q214
    (
        "Massage primarily enhances lymphatic and cardiovascular systems through mechanical and physiological mechanisms. Lymphatic benefits include improved drainage, reduced swelling, enhanced immune function, and toxin removal through manual manipulation of lymph vessels and nodes. Cardiovascular improvements include increased venous return, enhanced circulation, reduced blood pressure, improved tissue oxygenation, and better nutrient delivery. The pumping action of massage techniques directly moves lymph and blood, while relaxation response improves heart rate variability and vascular tone. These two systems work synergistically - better circulation supports lymphatic function, while lymphatic drainage reduces cardiovascular workload.",
        "🎯 **Key Concept**: Massage primarily enhances lymphatic and cardiovascular systems through mechanical and physiological mechanisms.\\n\\n💡 **Memory Tip**: Massage = L♥️ (Love): Lymphatic drainage + Cardiovascular circulation = the heart of massage benefits!\\n\\n⚠️ **Exam Alert**: Lymphatic benefits include improved drainage, reduced swelling, enhanced immune function, and toxin removal. Cardiovascular improvements include increased venous return, enhanced circulation, reduced blood pressure, improved tissue oxygenation, and better nutrient delivery.\\n\\n✅ **Why Correct**: The pumping action of massage techniques directly moves lymph and blood. These two systems work synergistically - better circulation supports lymphatic function, while lymphatic drainage reduces cardiovascular workload."
    ),
    # Q215
    (
        "Treating edema requires understanding lymphatic drainage principles. The correct sequence is proximal-distal-proximal because lymphatic vessels have one-way valves directing fluid toward the heart. First, work proximally to 'clear the highway' - opening lymph nodes and vessels near the trunk to create space for fluid movement. Second, work distally to mobilize trapped fluid from swollen areas. Finally, work proximally again to guide the mobilized fluid toward the lymph nodes and venous return. This prevents 'traffic jams' where fluid has nowhere to go if you start distally first. The technique requires gentle pressure since lymphatic vessels are superficial and delicate.",
        "🎯 **Key Concept**: Treating edema requires the correct sequence: proximal-distal-proximal because lymphatic vessels have one-way valves directing fluid toward the heart.\\n\\n💡 **Memory Tip**: Edema direction = GPS: Go Proximal first (clear the highway), then Push fluid from distal, then Proximal finish (guide it home).\\n\\n⚠️ **Exam Alert**: First, work proximally to 'clear the highway' - opening lymph nodes and vessels near the trunk. Second, work distally to mobilize trapped fluid. Finally, work proximally again to guide the mobilized fluid toward lymph nodes and venous return.\\n\\n✅ **Why Correct**: This prevents 'traffic jams' where fluid has nowhere to go if you start distally first. The technique requires gentle pressure since lymphatic vessels are superficial and delicate."
    ),
    # Q216
    (
        "The hepatic portal system directs blood from digestive organs directly to the liver before returning to systemic circulation. This unique vascular arrangement allows the liver to process absorbed nutrients, detoxify substances, and regulate blood glucose before these materials enter general circulation. Blood from stomach, small intestine, large intestine, pancreas, and spleen drains into the hepatic portal vein, which carries it to liver sinusoids. Here, hepatocytes metabolize nutrients, neutralize toxins, and store/release glucose as needed. Only after hepatic processing does blood continue via hepatic veins to the inferior vena cava and heart. This 'first-pass' metabolism is crucial for protecting the body from potentially harmful absorbed substances.",
        "🎯 **Key Concept**: The hepatic portal system directs blood from digestive organs directly to the liver before returning to systemic circulation.\\n\\n💡 **Memory Tip**: Digestive blood takes a LIVER detour - think 'food goes to stomach, blood goes to liver for processing' - hepatic portal system!\\n\\n⚠️ **Exam Alert**: Blood from stomach, small intestine, large intestine, pancreas, and spleen drains into the hepatic portal vein, which carries it to liver sinusoids. Here, hepatocytes metabolize nutrients, neutralize toxins, and store/release glucose.\\n\\n✅ **Why Correct**: Only after hepatic processing does blood continue to the heart. This 'first-pass' metabolism is crucial for protecting the body from potentially harmful absorbed substances."
    ),
    # Q218
    (
        "The nervous system divides into CNS (central) and PNS (peripheral). CNS includes brain, brainstem, spinal cord, and white/gray matter within them. PNS includes everything outside the brain and spinal cord: cranial nerves (12 pairs), spinal nerves, ganglia, and peripheral receptors. Cranial nerves emerge from the brain but extend into peripheral tissues, making them PNS structures. This distinction is crucial for understanding nerve pathology and massage contraindications.",
        "🎯 **Key Concept**: The nervous system divides into CNS (central) and PNS (peripheral). Cranial nerves emerge from the brain but extend into peripheral tissues, making them PNS structures.\\n\\n💡 **Memory Tip**: CNS is Central (brain & cord), PNS is Peripheral (nerves escape!). Think: Cranial nerves 'Creep' out of the skull into the PNS!\\n\\n⚠️ **Exam Alert**: CNS includes brain, brainstem, spinal cord, and white/gray matter within them. PNS includes everything outside: cranial nerves (12 pairs), spinal nerves, ganglia, and peripheral receptors.\\n\\n✅ **Why Correct**: This distinction is crucial for understanding nerve pathology and massage contraindications."
    ),
    # Q219
    (
        "The knee has two C-shaped menisci: medial (tibial side) and lateral (fibular side). The lateral meniscus is more O-shaped and mobile, while the medial is more C-shaped and firmly attached. The fibular side refers to the outer/lateral aspect of the knee where the fibula is located. These cartilage discs act as shock absorbers and improve joint congruency. Lateral meniscus tears are common in sports injuries, making this knowledge clinically relevant for massage therapists.",
        "🎯 **Key Concept**: The knee has two C-shaped menisci: medial (tibial side) and lateral (fibular side). The lateral meniscus is on the fibular (outer) side.\\n\\n💡 **Memory Tip**: Lateral = fibLar side! Both have 'L'! Picture a crescent moon on the 'L'ateral side - Lateral meniscus!\\n\\n⚠️ **Exam Alert**: The lateral meniscus is more O-shaped and mobile, while the medial is more C-shaped and firmly attached. These cartilage discs act as shock absorbers and improve joint congruency.\\n\\n✅ **Why Correct**: Lateral meniscus tears are common in sports injuries, making this knowledge clinically relevant for massage therapists."
    ),
    # Q220
    (
        "Direct pressure over bony prominences of the spine can cause injury. Skin rolling is ideal over the spine because it lifts skin and superficial fascia away from underlying bone, avoiding direct pressure on vertebrae. Petrissage involves compression and kneading that could compress vertebrae, while friction involves direct pressure and movement over structures. The spinous processes are subcutaneous and vulnerable to trauma. Skin rolling promotes circulation and fascial mobility without risk to vertebral structures.",
        "🎯 **Key Concept**: Skin rolling is ideal over the spine because it lifts skin and superficial fascia away from underlying bone, avoiding direct pressure on vertebrae.\\n\\n💡 **Memory Tip**: Spine needs gentle 'SKIN rolling' - never 'SQUEEZE' (petrissage) or 'SCRAPE' (friction) the spine bones!\\n\\n⚠️ **Exam Alert**: Direct pressure over bony prominences of the spine can cause injury. Petrissage involves compression that could compress vertebrae, while friction involves direct pressure on structures.\\n\\n✅ **Why Correct**: The spinous processes are subcutaneous and vulnerable to trauma. Skin rolling promotes circulation and fascial mobility without risk to vertebral structures."
    ),
    # Q221
    (
        "In Traditional Chinese Medicine, Shu points are located on the bladder meridian and correspond to organ systems. The upper burner includes lung and heart systems. The medial tip of the scapular spine serves as a horizontal landmark at approximately T3 vertebral level, where BL-13 (Lung Shu) is located. This anatomical landmark helps practitioners locate the correct point for treatment. The scapular spine is easily palpable and provides a reliable reference for finding upper burner Shu points.",
        "🎯 **Key Concept**: The medial tip of the scapular spine serves as a horizontal landmark at approximately T3 vertebral level, where BL-13 (Lung Shu) is located.\\n\\n💡 **Memory Tip**: Scapula Spine = Upper burner line! 'LUNG lives at scapuLa Line' - BL-13 at T3 level, scapular spine level!\\n\\n⚠️ **Exam Alert**: In Traditional Chinese Medicine, Shu points are located on the bladder meridian and correspond to organ systems. The upper burner includes lung and heart systems.\\n\\n✅ **Why Correct**: The scapular spine is easily palpable and provides a reliable reference for finding upper burner Shu points."
    ),
    # Q222
    (
        "Dupuytren's Contracture involves progressive thickening and shortening of the palmar fascia, creating fibrous cords that pull fingers into flexion. The primary pathology is in the palmar fascia, not joints or general finger mobility. Cross-fiber friction specifically targets the thickened fascial bands, helping to break up adhesions and maintain tissue mobility. This technique addresses the root cause - the fascial contracture. Passive ROM to wrist doesn't target the palm pathology, and general finger ROM doesn't address the specific fascial restriction.",
        "🎯 **Key Concept**: Dupuytren's Contracture involves progressive thickening and shortening of the palmar fascia, creating fibrous cords that pull fingers into flexion.\\n\\n💡 **Memory Tip**: Dupuytren's = 'Palmar fascia Problem' - needs 'Friction to Fascia' to break up the fibrous bands!\\n\\n⚠️ **Exam Alert**: The primary pathology is in the palmar fascia, not joints or general finger mobility. Cross-fiber friction specifically targets the thickened fascial bands, helping to break up adhesions and maintain tissue mobility.\\n\\n✅ **Why Correct**: This technique addresses the root cause - the fascial contracture. Passive ROM to wrist doesn't target the palm pathology, and general finger ROM doesn't address the specific fascial restriction."
    ),
    # Q223
    (
        "In Traditional Chinese Medicine, meridians are energy pathways that flow through the body. The Liver and Kidney meridians both travel along the medial (inner) thigh where the adductor muscle group is located. The Liver meridian runs along the medial leg and thigh, while the Kidney meridian also follows the inner leg pathway. The adductor muscles (adductor longus, brevis, magnus, gracilis, pectineus) are located on the medial thigh and work to pull the leg toward the body's midline. Understanding meridian pathways is essential for massage therapists practicing Eastern modalities or incorporating TCM principles into treatment.",
        "🎯 **Key Concept**: The Liver and Kidney meridians both travel along the medial (inner) thigh where the adductor muscle group is located.\\n\\n💡 **Memory Tip**: LAKE - Liver And Kidney Experience the adductors (both flow through the inner thigh where adductors live).\\n\\n⚠️ **Exam Alert**: The Liver meridian runs along the medial leg and thigh, while the Kidney meridian also follows the inner leg pathway. The adductor muscles are located on the medial thigh.\\n\\n✅ **Why Correct**: Understanding meridian pathways is essential for massage therapists practicing Eastern modalities or incorporating TCM principles into treatment."
    ),
    # Q224
    (
        "The triceps brachii is the primary muscle responsible for elbow extension (straightening). Located on the posterior arm, it has three heads: long head, lateral head, and medial head, all converging to insert on the olecranon process of the ulna. When contracted, the triceps pulls the forearm away from the upper arm, creating extension at the elbow joint. This is opposite to flexion (bending) performed by the biceps and brachialis. The triceps is crucial for pushing movements and activities requiring arm extension. Massage therapists frequently work on tight triceps, especially in clients who perform repetitive pushing motions or hold extended arm positions.",
        "🎯 **Key Concept**: The triceps brachii is the primary muscle responsible for elbow extension (straightening).\\n\\n💡 **Memory Tip**: TRI-ceps has THREE heads to EXTEND your reach (think of reaching out to extend your arm).\\n\\n⚠️ **Exam Alert**: Located on the posterior arm, it has three heads: long head, lateral head, and medial head, all converging to insert on the olecranon process of the ulna. When contracted, the triceps pulls the forearm away from the upper arm.\\n\\n✅ **Why Correct**: The triceps is crucial for pushing movements. Massage therapists frequently work on tight triceps, especially in clients who perform repetitive pushing motions or hold extended arm positions."
    ),
    # Q225
    (
        "Lymphatic vessels travel alongside veins, not arteries, as they return lymph to the cardiovascular system. Both lymphatic vessels and veins are low-pressure systems carrying fluid back toward the heart, making them natural travel companions. Arteries carry high-pressure oxygenated blood away from the heart, while veins and lymphatics both use similar mechanisms (muscle contractions, one-way valves, breathing) to move their contents toward the heart against gravity. The lymphatic system ultimately drains into the venous system at the subclavian veins. This anatomical relationship is important for massage therapists when performing lymphatic drainage techniques.",
        "🎯 **Key Concept**: Lymphatic vessels travel alongside veins, not arteries, as they return lymph to the cardiovascular system.\\n\\n💡 **Memory Tip**: Veins and lymph are VEIN-mates - they're both heading home to the heart together (low pressure buddies).\\n\\n⚠️ **Exam Alert**: Both lymphatic vessels and veins are low-pressure systems carrying fluid back toward the heart. They both use similar mechanisms: muscle contractions, one-way valves, and breathing to move their contents toward the heart against gravity.\\n\\n✅ **Why Correct**: The lymphatic system ultimately drains into the venous system at the subclavian veins. This anatomical relationship is important for massage therapists when performing lymphatic drainage techniques."
    ),
]

# Apply conversions
for old_text, new_text in conversions:
    old_escaped = re.escape(old_text)
    content = re.sub(old_escaped, new_text, content)

# Write the file back
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("Conversion complete for questions 211-225!")
