#!/usr/bin/env python3
"""
Convert topic_explanation fields for questions 149-192 to beautiful markdown format.
This script reads the actual current text from the file and converts it.
"""

# Read the file
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Define all conversions based on actual current text
conversions = [
    {
        "qid": 149,
        "old": "The skin has four primary functions, but absorption is the least important. Protection is crucial (barrier against pathogens, UV, chemicals). Heat regulation is vital for homeostasis through sweating and vasodilation. Sensation provides critical environmental awareness through numerous receptors. While skin can absorb some substances (medications, chemicals), this function is limited compared to other organs like intestines. The skin's barrier function actually works to PREVENT absorption of most substances, making absorption the least significant of its roles.",
        "new": "🎯 **Key Concept**: Skin's main functions are **P**rotection, **H**eat regulation, and **S**ensation. **Absorption is the LEAST important** - skin is designed as a barrier, not for absorption.\\n\\n💡 **Memory Tip**: PHS - Protection, Heat regulation, Sensation are the skin's main mission! Absorption is limited - not the skin's best transmission!\\n\\n⚠️ **Exam Alert**: While skin can absorb some substances (medications, chemicals), this function is limited compared to intestinal absorption. The barrier function actually PREVENTS most absorption.\\n\\n✅ **Why Correct**: Protection (barrier against pathogens, UV), heat regulation (homeostasis through sweating/vasodilation), and sensation (environmental awareness through receptors) are vital survival functions - absorption is the least significant role."
    },
    {
        "qid": 150,
        "old": "Migraine headaches involve vascular changes including vasodilation in the head and neck region. Heat application to the head would worsen symptoms by further dilating blood vessels and increasing pain intensity. Cold therapy is appropriate as it causes vasoconstriction, reducing inflammation and pain. Foot and hand work are excellent alternatives, providing therapeutic benefit through reflexology points and nervous system calming without aggravating head sensitivity. Always avoid heat on the head/neck area during acute migraine episodes.",
        "new": "🎯 **Key Concept**: Heat packs to the head are **CONTRAINDICATED** for migraines. Heat causes vasodilation (blood vessel expansion), worsening the throbbing pain from already dilated vessels.\\n\\n💡 **Memory Tip**: Cool Head Hot Feet - Migraines need COOL on the head, never heat! Heat makes blood vessels expand and pain compete!\\n\\n⚠️ **Exam Alert**: Cold packs cause vasoconstriction (reducing inflammation and pain). Foot and hand work using reflexology is excellent for migraines.\\n\\n✅ **Why Correct**: Migraines involve vascular changes with dilated head/neck blood vessels. Adding heat further dilates vessels and increases pain. Cold therapy and reflexology provide relief without aggravating head sensitivity."
    },
    {
        "qid": 151,
        "old": "Numbness indicates compromised nerve function or circulation. Effleurage, with its long, gentle, gliding strokes, is ideal because it stimulates blood flow and nerve pathways without overwhelming compromised tissues. This technique promotes circulation, encourages lymphatic drainage, and provides gentle sensory input to help restore nerve function. Aggressive techniques could damage already compromised nerves or tissues. Effleurage's light to moderate pressure and continuous contact help re-establish nerve pathways safely while improving circulation to the affected area.",
        "new": "🎯 **Key Concept**: Numbness indicates compromised nerve function requiring **gentle effleurage** - long, gliding strokes that safely stimulate blood flow and nerve pathways without overwhelming compromised tissues.\\n\\n💡 **Memory Tip**: Numb Needs Nice - When sensation is gone, use EFFLEURAGE gentle and long! Light touch awakens nerves without alarm!\\n\\n⚠️ **Exam Alert**: Avoid aggressive techniques! Trigger point, tapotement, and deep friction could damage already compromised nerves or tissues.\\n\\n✅ **Why Correct**: Effleurage promotes circulation, encourages lymphatic drainage, and provides gentle sensory input to help restore nerve function. Light to moderate pressure and continuous contact re-establish nerve pathways safely."
    },
    {
        "qid": 152,
        "old": "HIV-positive clients require gentle, non-invasive approaches due to compromised immune systems and increased sensitivity. Easy bruising indicates fragile capillaries and poor clotting. Neuralgia involves nerve pain requiring gentle handling. Poor circulation necessitates techniques that promote flow without tissue damage. Polarity therapy works with energy fields without direct tissue manipulation, making it safe for all these concerns. Direct pressure techniques (effleurage, friction, tapotement) risk bruising and tissue damage in immunocompromised clients with fragile tissues and reduced healing capacity.",
        "new": "🎯 **Key Concept**: HIV clients with easy bruising, neuralgia, and circulation concerns need **polarity therapy** - energy work WITHOUT direct tissue manipulation, protecting fragile capillaries and compromised immune systems.\\n\\n💡 **Memory Tip**: PALE HIV clients need Polarity: **P**-ale skin (bruises), **A**-che (neuralgia), **L**-eg circulation, **E**-nergy work. Direct touch techniques are too harsh!\\n\\n⚠️ **Exam Alert**: Effleurage, friction, and tapotement all risk bruising and tissue damage in immunocompromised clients with fragile tissues and reduced healing capacity.\\n\\n✅ **Why Correct**: Polarity therapy works with energy fields without direct pressure, making it safe for all concerns: poor circulation, nerve pain, easy bruising, and compromised immune function."
    },
    {
        "qid": 153,
        "old": "In Traditional Chinese Medicine, the liver system governs the eyes and vision. The liver meridian terminates at the eye, making eye conditions like conjunctivitis indicators of liver imbalance. Conjunctivitis (pink eye) with redness and inflammation suggests 'liver heat' or 'liver fire rising' in TCM terminology. The liver controls the smooth flow of qi and blood throughout the body; when this function is disrupted (from stress, anger, or poor diet), heat can accumulate and rise to the eyes, causing inflammation. Treatment would focus on clearing liver heat and regulating liver qi.",
        "new": "🎯 **Key Concept**: In Traditional Chinese Medicine, the **Liver meridian governs the eyes**. Conjunctivitis (pink eye) indicates Liver heat or Liver fire rising.\\n\\n💡 **Memory Tip**: LIVER sees ALL! **L**-iver controls **L**-ight (vision), **I**-nflammation in eyes, **V**-ision problems, **E**-ye redness, **R**-age (liver emotion affects eyes). When liver is hot, eyes get red!\\n\\n⚠️ **Exam Alert**: Heart → tongue/speech, Lung → skin/breathing, Spleen → digestion/muscle. Only Liver connects to eyes.\\n\\n✅ **Why Correct**: The Liver meridian terminates at the eye. When liver qi is disrupted (from stress, anger, poor diet), heat accumulates and rises to the eyes, causing inflammation. Treatment clears Liver heat."
    },
    {
        "qid": 154,
        "old": "Herniated annulus fibrosis refers to disc herniation where the tough outer ring (annulus fibrosis) tears, allowing inner nucleus pulposus to protrude. This herniation commonly compresses spinal nerve roots, particularly the sciatic nerve, causing radicular pain (radiating down the leg) and neurological symptoms like numbness. The pain follows dermatomal patterns corresponding to the compressed nerve. Osgood-Schlatter's disease affects the tibial tuberosity in adolescents, causing localized knee pain. Chondromalacia patella involves knee cartilage degeneration with anterior knee pain. Neither causes posterior leg radiation with numbness characteristic of nerve root compression from disc herniation.",
        "new": "🎯 **Key Concept**: Pain radiating down posterior leg with numbness = **herniated annulus fibrosus** (disc herniation) compressing the sciatic nerve root.\\n\\n💡 **Memory Tip**: HERNIATED disc = RADIATED pain! **H**-erniated annulus, **E**-xtreme pain, **R**-adiation down leg, **N**-umbness follows, **I**-mpinged nerve, **A**-nnulus torn, **T**-ingling, **E**-verything shoots Down!\\n\\n⚠️ **Exam Alert**: Osgood-Schlatter's = localized knee pain in adolescents. Chondromalacia patella = anterior knee pain. Neither causes posterior leg radiation or numbness.\\n\\n✅ **Why Correct**: When the tough outer ring (annulus fibrosus) tears, the inner nucleus pulposus protrudes and compresses nerve roots. This causes radicular pain (following dermatomal patterns) and neurological symptoms like numbness."
    },
    {
        "qid": 155,
        "old": "Short gliding strokes are optimal for trigger point location because they allow precise palpation of small, localized areas of muscle tension. Trigger points are small, hyperirritable nodules within taut muscle bands - typically pea-sized or smaller. Short strokes enable the therapist to detect subtle changes in tissue texture, density, and temperature that indicate trigger points. These strokes move slowly across muscle fibers, providing focused assessment. Deep petrissage covers too large an area and lacks precision. Effleurage's long strokes would glide over trigger points without detecting them. The key is small, controlled movements for accurate identification.",
        "new": "🎯 **Key Concept**: Finding trigger points requires **short gliding strokes** - slow, controlled movements that detect subtle texture changes in small, localized areas.\\n\\n💡 **Memory Tip**: SHORT and SWEET finds the SPOT! Short Gliding = Spot Finding. Like a detective using SHORT steps to find clues - long strokes MISS tiny trigger points!\\n\\n⚠️ **Exam Alert**: Deep petrissage covers too large an area and lacks precision. Effleurage's long strokes glide over trigger points without detecting them.\\n\\n✅ **Why Correct**: Trigger points are small, hyperirritable nodules (typically pea-sized) within taut muscle bands. Short strokes move slowly across fibers, detecting subtle changes in tissue texture, density, and temperature. Small, controlled movements ensure accurate identification."
    },
    {
        "qid": 156,
        "old": "Dark circles under eyes and low back pain indicate kidney/bladder system deficiency in TCM. The kidney meridian governs the low back region and controls essence (jing) which affects aging processes visible in dark under-eye circles. When kidney qi is deficient, tonification is needed to strengthen and build these systems. Tonify techniques include gentle, sustained pressure along meridian pathways, moving in the direction of qi flow, often combined with moxa heat. This adds energy to depleted systems. Dispersal techniques would further weaken deficient conditions. Stomach/Spleen meridians relate to digestive issues, not these symptoms of kidney depletion.",
        "new": "🎯 **Key Concept**: Dark circles under eyes + low back ache = **Kidney/Bladder (KI/BL) deficiency**. Treatment: **TONIFY** to strengthen and build up depleted energy.\\n\\n💡 **Memory Tip**: BLADDER-KIDNEY need BOOST! **B**-ack pain, **L**-ow energy, dark circles = **A**-ging kidneys, **D**-ark circles, **D**-epletion, **E**-xhaustion, **R**-enal weakness. TONIFY what's weak!\\n\\n⚠️ **Exam Alert**: Dispersal would WEAKEN an already deficient system. Stomach/Spleen relate to digestion, not these kidney depletion symptoms.\\n\\n✅ **Why Correct**: Kidney meridian governs low back and controls essence (jing) affecting aging processes (visible in dark circles). Tonification (gentle, sustained pressure along meridian pathways, moxa heat) adds energy to depleted systems."
    },
    {
        "qid": 157,
        "old": "In Traditional Chinese Medicine, the Kidney (KI) meridian governs the ears and hearing function. The kidneys store essence (jing) which nourishes the brain and sensory organs, particularly the ears. Bilateral hearing loss (both ears affected) indicates kidney deficiency - the kidneys lack sufficient essence to nourish the ears. This connection is why age-related hearing loss is common as kidney essence naturally depletes with aging. The kidney meridian pathway includes connections to the ears. Treatment focuses on tonifying kidney qi and essence through acupressure, diet, and lifestyle modifications. Other meridians (Liver-eyes, Spleen-muscles, Heart-tongue) don't govern hearing.",
        "new": "🎯 **Key Concept**: In TCM, the **Kidney (KI) meridian governs the ears and hearing**. Bilateral hearing loss = Kidney deficiency - insufficient essence to nourish the ears.\\n\\n💡 **Memory Tip**: KIDNEY = KEY to hearing! **K**-idney **E**-ssence **Y**-ields hearing. Age-related hearing loss = Kidney essence decline with aging.\\n\\n⚠️ **Exam Alert**: Liver → eyes/vision, Spleen → muscles/digestion, Heart → tongue/speech. Only Kidney controls ears and hearing.\\n\\n✅ **Why Correct**: Kidneys store essence (jing) which nourishes the brain and sensory organs, particularly ears. The Kidney meridian pathway includes connections to the ears. Treatment tonifies Kidney qi and essence through acupressure, diet, and lifestyle."
    },
    {
        "qid": 158,
        "old": "The iliopsoas is a major hip flexor connecting the lumbar spine to the femur. When shortened/tight, it creates anterior pelvic tilt by pulling the pelvis forward and increasing lumbar lordosis (swayback). Prolonged sitting is a primary cause of iliopsoas tightness. The shortened muscle maintains constant tension, pulling the lumbar vertebrae forward and tilting the pelvis anteriorly. This compensatory pattern creates excessive lumbar curve, leading to low back pain and postural dysfunction. Other hip flexors contribute, but iliopsoas is the strongest and most direct connection between spine and leg, making it the primary culprit in anterior pelvic tilt.",
        "new": "🎯 **Key Concept**: Shortened **iliopsoas** creates **anterior pelvic tilt** - pulling the pelvis forward and increasing lumbar lordosis (swayback), leading to low back pain.\\n\\n💡 **Memory Tip**: SITTING SHORTENS iliopsoas! Prolonged sitting = tight hip flexor = pelvis tilts ANTERIOR (forward) = swayback curve.\\n\\n⚠️ **Exam Alert**: Iliopsoas is the major hip flexor connecting lumbar spine to femur - the strongest and most direct connection between spine and leg.\\n\\n✅ **Why Correct**: When iliopsoas is tight, it maintains constant tension pulling lumbar vertebrae forward and tilting pelvis anteriorly. This compensatory pattern creates excessive lumbar curve and postural dysfunction. Other hip flexors contribute, but iliopsoas is the primary culprit."
    },
    {
        "qid": 159,
        "old": "Hypertensive clients require careful treatment modifications, especially avoiding deep abdominal massage. Deep pressure in the abdomen can stimulate the vagus nerve, triggering a parasympathetic response that can cause sudden blood pressure changes. In hypertensive clients with already compromised cardiovascular regulation, this could trigger dangerous fluctuations including sudden drops (vasovagal response) or spikes. The abdomen contains major blood vessels (aorta, inferior vena cava) and organs. Deep abdominal work risks overstimulation of baroreceptors and autonomic reflexes. Light, gentle abdominal work may be appropriate, but deep pressure is contraindicated for client safety.",
        "new": "🎯 **Key Concept**: **AVOID deep abdominal massage** for hypertensive clients. Deep pressure can stimulate the vagus nerve, triggering dangerous blood pressure fluctuations.\\n\\n💡 **Memory Tip**: DEEP ABDOMEN = DANGER for high BP! Vagus nerve stimulation → sudden BP changes (drops or spikes) in compromised cardiovascular systems.\\n\\n⚠️ **Exam Alert**: The abdomen contains major blood vessels (aorta, inferior vena cava) and organs. Deep work risks overstimulation of baroreceptors and autonomic reflexes.\\n\\n✅ **Why Correct**: Deep abdominal pressure triggers parasympathetic response (vasovagal) in hypertensive clients with already compromised cardiovascular regulation. Light, gentle abdominal work may be appropriate, but deep pressure is contraindicated for safety."
    },
    {
        "qid": 160,
        "old": "Pain during both active and passive movement indicates joint or ligament pathology. Active movement (client-initiated) tests muscles, while passive movement (therapist-initiated) tests joint structures. If both movements hurt, the problem isn't muscular (which would only hurt during active motion when muscles contract). Instead, pain during both indicates joint capsule, ligament, or articular cartilage damage - these structures are stressed regardless of who initiates movement. This differential assessment helps identify tissue type involved: muscle/tendon pain = active only; joint/ligament pain = both active and passive. This guides referral and treatment decisions.",
        "new": "🎯 **Key Concept**: Pain during **BOTH active AND passive movement** = **joint or ligament pathology**. If both movements hurt, it's NOT muscular - it's joint structures.\\n\\n💡 **Memory Tip**: BOTH movements = BOTH types of structures! Active only = muscle issue. Active + Passive = joint/ligament issue.\\n\\n⚠️ **Exam Alert**: Active movement tests muscles (client-initiated). Passive movement tests joint structures (therapist-initiated). Muscles only contract during active motion.\\n\\n✅ **Why Correct**: Joint capsule, ligaments, and articular cartilage are stressed regardless of who initiates movement. This differential assessment identifies tissue type: muscle/tendon (active only) vs. joint/ligament (both active and passive). Guides referral and treatment decisions."
    },
]

# Continue with remaining questions 161-192
conversions.extend([
    {
        "qid": 161,
        "old": "Chronic Achilles tendonitis requires specific treatment: dorsiflex the foot to lengthen the Achilles tendon, then apply cross-friction massage. Dorsiflexion (toes toward shin) stretches the Achilles and gastrocnemius/soleus complex, exposing the tendon fibers and putting them under slight tension for optimal treatment. Cross-fiber friction applied perpendicular to tendon fibers helps break up adhesions, realign scar tissue, and stimulate healing in chronic cases. This combination addresses the fibrous restrictions that develop in chronic tendonitis. Plantar flexion would shorten the tendon, making friction less effective. Simple friction without positioning wouldn't adequately address the tendon length.",
        "new": "🎯 **Key Concept**: Chronic Achilles tendonitis treatment: **dorsiflex the foot** (toes toward shin) to lengthen/stretch the tendon, THEN apply **cross-friction massage**.\\n\\n💡 **Memory Tip**: STRETCH then SCRUB! Dorsiflex = stretch tendon, then cross-friction = scrub away adhesions. Like stretching fabric before ironing out wrinkles!\\n\\n⚠️ **Exam Alert**: Plantar flexion would SHORTEN the tendon, making friction less effective. Dorsiflexion puts fibers under slight tension for optimal treatment.\\n\\n✅ **Why Correct**: Dorsiflexion stretches the Achilles and gastrocnemius/soleus complex, exposing tendon fibers. Cross-fiber friction (perpendicular to fibers) breaks up adhesions, realigns scar tissue, and stimulates healing in chronic cases."
    },
    {
        "qid": 162,
        "old": "Chronic tendinitis requires a two-phase approach. Friction massage breaks up adhesions, increases circulation, and stimulates healing in chronically inflamed tendons. However, friction creates temporary inflammation and microtrauma. Following friction with ice application provides cryotherapy benefits: reduces inflammation, controls swelling, numbs pain, and prevents excessive inflammatory response to the friction treatment. This ice-friction combination is standard protocol for chronic tendon conditions. The friction stimulates tissue remodeling while ice keeps inflammation controlled, maximizing therapeutic benefits while minimizing adverse reactions. Heat would increase inflammation. Stretching before friction doesn't address the adhesions.",
        "new": "🎯 **Key Concept**: Chronic tendinitis treatment: **friction massage** to break up adhesions, THEN **ice** to control the inflammation created by friction.\\n\\n💡 **Memory Tip**: FRICTION then FREEZE! Friction breaks up scar tissue (creates temporary inflammation), then Ice controls the swelling and inflammation. Standard two-phase protocol!\\n\\n⚠️ **Exam Alert**: Heat would INCREASE inflammation - wrong choice! Stretching before friction doesn't address the adhesions.\\n\\n✅ **Why Correct**: Friction increases circulation and stimulates healing but creates microtrauma. Ice provides cryotherapy: reduces inflammation, controls swelling, numbs pain, prevents excessive inflammatory response. This combination maximizes therapeutic benefits while minimizing adverse reactions."
    },
    {
        "qid": 163,
        "old": "The medial elbow is the anatomical pathway for Heart (HT) and Small Intestine (SI) meridians in Traditional Chinese Medicine. The Heart meridian runs along the medial arm from axilla to little finger, passing through the medial elbow region. The Small Intestine meridian (Heart's paired Yang organ) also travels along the medial upper extremity. Both meridians converge at the medial elbow area. Other meridians like Large Intestine and Lung travel along the lateral and anterior arm, not medial elbow. Understanding meridian pathways helps massage therapists locate acupressure points and explain referred pain patterns in TCM framework.",
        "new": "🎯 **Key Concept**: The **medial elbow** is the anatomical pathway for **Heart (HT) and Small Intestine (SI) meridians** in Traditional Chinese Medicine.\\n\\n💡 **Memory Tip**: HEART on MEDIAL! Heart meridian runs along medial arm from axilla to little finger, passing through medial elbow. SI (Heart's paired Yang organ) also travels medial arm.\\n\\n⚠️ **Exam Alert**: Large Intestine and Lung meridians travel lateral and anterior arm, NOT medial elbow.\\n\\n✅ **Why Correct**: Both HT and SI meridians converge at the medial elbow area. Understanding meridian pathways helps locate acupressure points and explain referred pain patterns in TCM framework."
    },
    {
        "qid": 164,
        "old": "Contracted muscles have shortened, tight tendons that require gentle, progressive treatment. Effleurage provides broad, flowing strokes that warm tissues, increase circulation, and prepare muscles for deeper work. These gentle, gliding movements help relax contracted tissue without forcing length changes that could cause injury. Starting with effleurage establishes rapport with tight tissue. Friction and petrissage are too aggressive for initial treatment of chronically shortened muscles - they could cause protective spasm or microtears. Stretching contracted muscles requires warming first. Effleurage is always the appropriate initial technique before progressing to deeper work.",
        "new": "🎯 **Key Concept**: Contracted muscles with tight tendons need **effleurage FIRST** - gentle, gliding strokes that warm tissues, increase circulation, and prepare for deeper work.\\n\\n💡 **Memory Tip**: WARM before WORK! Effleurage = warm-up for tight tissues. Don't force contracted muscles - ease them open gently first!\\n\\n⚠️ **Exam Alert**: Friction and petrissage are TOO AGGRESSIVE for initial treatment. They could cause protective spasm or microtears in chronically shortened muscles.\\n\\n✅ **Why Correct**: Effleurage provides broad, flowing strokes that relax contracted tissue without forcing length changes. Establishes rapport with tight tissue. Always the appropriate initial technique before progressing to stretching or deeper work."
    },
    {
        "qid": 165,
        "old": "In Traditional Chinese Medicine, each meridian has a two-hour peak function period following the Chinese Medicine Clock. The Triple Energizer (TE) meridian, also called San Jiao or Triple Warmer, peaks from 9-11 PM. This meridian doesn't correspond to a specific physical organ but regulates the three 'burners' (upper, middle, lower body regions) controlling metabolism, fluid distribution, and temperature regulation. The 9-11 PM peak time is significant for thermoregulation and preparing the body for rest. Understanding meridian clock timing helps therapists schedule treatments and explain symptom patterns that worsen at specific times.",
        "new": "🎯 **Key Concept**: The **Triple Energizer (TE) meridian** peaks from **9-11 PM** on the Chinese Medicine Clock. It regulates metabolism, fluid distribution, and temperature.\\n\\n💡 **Memory Tip**: 9 to 11 PM = TRIPLE E time! **T**riple **E**nergizer = **E**vening regulation (9-11 PM) preparing body for rest.\\n\\n⚠️ **Exam Alert**: Triple Energizer (San Jiao/Triple Warmer) doesn't correspond to a specific physical organ - it regulates three 'burners' (upper, middle, lower body regions).\\n\\n✅ **Why Correct**: The TE meridian controls thermoregulation and prepares the body for rest during its 9-11 PM peak. Understanding meridian clock timing helps therapists schedule treatments and explain symptom patterns that worsen at specific times."
    },
    {
        "qid": 166,
        "old": "In TCM's Five Element theory, the Heart (HT) controls the Spleen through the control cycle (Ke cycle). The Heart represents Fire element, while Spleen represents Earth element. In the control cycle, Fire controls (melts/dominates) Earth - meaning Heart energy can regulate or suppress Spleen function. This is distinct from the nourishing cycle where elements support each other. The control cycle maintains balance by preventing any element from becoming excessive. This relationship explains how emotional stress (Heart) can affect digestion (Spleen), or how cardiovascular issues might impact digestive function in TCM diagnosis and treatment.",
        "new": "🎯 **Key Concept**: In TCM Five Element theory, **Heart (HT) controls Spleen** through the control cycle (Ke cycle). Fire element (Heart) controls/dominates Earth element (Spleen).\\n\\n💡 **Memory Tip**: FIRE melts EARTH! Heart (Fire) can regulate or suppress Spleen (Earth) function. Think volcano melting earth!\\n\\n⚠️ **Exam Alert**: This is the CONTROL cycle (Ke), not the nourishing cycle. Control cycle maintains balance by preventing elements from becoming excessive.\\n\\n✅ **Why Correct**: This relationship explains how emotional stress (Heart) affects digestion (Spleen), or how cardiovascular issues impact digestive function in TCM diagnosis. Fire controls Earth to maintain balance."
    },
    {
        "qid": 167,
        "old": "In Traditional Chinese Medicine, Yin energy flows from inferior to superior (bottom to top) while Yang energy flows superior to inferior. Yin represents qualities like coolness, darkness, receptivity, and ascending movement. Yang represents heat, light, activity, and descending movement. This directional flow is fundamental to meridian pathways and energy work. Yin meridians (Lung, Spleen, Heart, Kidney, Liver, Pericardium) flow upward along the body's anterior and medial aspects. Understanding these flow patterns guides acupressure application - working with meridian flow for tonification, against flow for dispersal.",
        "new": "🎯 **Key Concept**: In TCM, **Yin energy flows INFERIOR to SUPERIOR (bottom to top)**. Yang energy flows superior to inferior (top to bottom).\\n\\n💡 **Memory Tip**: YIN = UPLIFTING! Yin rises UP like cool mist rising from water. Yang descends DOWN like hot sun rays falling to earth.\\n\\n⚠️ **Exam Alert**: Yin meridians (Lung, Spleen, Heart, Kidney, Liver, Pericardium) flow UPWARD along body's anterior and medial aspects.\\n\\n✅ **Why Correct**: Yin represents coolness, darkness, receptivity, and ASCENDING movement. This directional flow is fundamental to meridian pathways. Understanding guides acupressure: working WITH meridian flow for tonification, AGAINST flow for dispersal."
    },
    {
        "qid": 168,
        "old": "In Traditional Chinese Medicine's Five Element Theory, Fire feeds Earth in the generative cycle. Fire burns organic matter to create ash and fertile soil, nourishing Earth. In TCM organ relationships, this means the Heart (Fire element) nourishes and supports the Spleen/Stomach (Earth element). Clinically, this explains how cardiovascular health affects digestive function, or how joy (Heart emotion) supports proper digestion. The generative cycle (also called nourishing or Sheng cycle) shows how each element creates and supports the next: Wood feeds Fire, Fire creates Earth, Earth bears Metal, Metal enriches Water, Water nourishes Wood.",
        "new": "🎯 **Key Concept**: In TCM Five Element Theory, **Fire feeds Earth** in the generative cycle (Sheng cycle). Heart (Fire) nourishes Spleen/Stomach (Earth).\\n\\n💡 **Memory Tip**: FIRE creates fertile EARTH! Fire burns wood → creates ASH → fertilizes SOIL. Heart (Fire) supports digestion (Earth).\\n\\n⚠️ **Exam Alert**: Generative cycle (nourishing): Wood→Fire→Earth→Metal→Water→Wood. Each element creates and supports the next.\\n\\n✅ **Why Correct**: Fire burns organic matter to create ash and fertile soil. Clinically: cardiovascular health (Heart) affects digestive function (Spleen), or how joy (Heart emotion) supports proper digestion. This is the creative, nourishing relationship."
    },
    {
        "qid": 169,
        "old": "Unilateral limb edema indicates local vascular pathology, specifically an occluded blood vessel (thrombosis, embolism, or compression). When liver, heart, or kidney dysfunction causes edema, it affects both limbs symmetrically because these are systemic conditions affecting whole-body fluid balance. Unilateral presentation means the problem is localized to one limb's vascular system - typically deep vein thrombosis (DVT) or lymphatic obstruction. This is a medical emergency requiring immediate referral as massage could dislodge a clot, causing pulmonary embolism. Never massage unilateral edema until vascular pathology is ruled out by medical evaluation.",
        "new": "🎯 **Key Concept**: **Unilateral (one-sided) limb edema** = **occluded blood vessel** (thrombosis, embolism, compression). This is a LOCAL vascular emergency, NOT systemic organ dysfunction.\\n\\n💡 **Memory Tip**: ONE swollen leg = ONE blocked vessel! Bilateral = systemic (liver, heart, kidney). Unilateral = LOCAL vascular pathology (DVT risk!).\\n\\n⚠️ **Exam Alert**: NEVER massage unilateral edema! Could dislodge clot → pulmonary embolism (life-threatening). Immediate medical referral required.\\n\\n✅ **Why Correct**: Liver, heart, kidney dysfunction causes BILATERAL (both limbs) edema - systemic whole-body fluid balance issues. Unilateral means localized vascular obstruction in one limb. Medical evaluation must rule out DVT before ANY massage."
    },
    {
        "qid": 170,
        "old": "When treating edema, work distal to proximal to promote lymphatic drainage and venous return. Start at the furthest point (hands/feet) and stroke toward the heart. This follows the natural direction of lymphatic and venous flow, helping move accumulated fluid out of tissues and back into circulation. Working proximal to distal would push fluid into already congested distal tissues, worsening swelling. The lymphatic system doesn't have a pump like the heart, so it relies on external pressure and proper directional flow. Always move fluid toward lymph nodes and ultimately toward the thoracic duct for reabsorption.",
        "new": "🎯 **Key Concept**: For edema treatment, work **DISTAL to PROXIMAL** (hands/feet → toward heart). This promotes lymphatic drainage and venous return.\\n\\n💡 **Memory Tip**: FLUSH toward the HEART! Start at the furthest point and stroke TOWARD the heart - following natural lymph/venous flow to move fluid OUT of tissues.\\n\\n⚠️ **Exam Alert**: Proximal to distal would PUSH fluid INTO already congested distal tissues, WORSENING swelling. Always move toward lymph nodes.\\n\\n✅ **Why Correct**: The lymphatic system has no pump (unlike the heart), so it relies on external pressure and proper directional flow. Distal to proximal helps move accumulated fluid back into circulation toward thoracic duct for reabsorption."
    },
    {
        "qid": 171,
        "old": "The Gallbladder (GB) meridian runs along the lateral aspect of the leg, making it the primary meridian associated with lateral leg pain in Traditional Chinese Medicine. The GB meridian pathway travels from the head, down the lateral side of the torso, and continues down the lateral thigh, knee, lower leg, and foot (ending at the 4th toe). Lateral leg pain, IT band issues, or lateral knee pain often indicate GB meridian imbalance. Treatment involves acupressure along GB points, particularly GB-34 (lateral knee) and GB-30 (hip). Understanding meridian pathways helps identify pain patterns and select appropriate treatment points.",
        "new": "🎯 **Key Concept**: The **Gallbladder (GB) meridian** runs along the **LATERAL leg**, making it the primary meridian for lateral leg pain in TCM.\\n\\n💡 **Memory Tip**: GB = GO LATERAL! Gallbladder meridian travels down the LATERAL side from head → torso → thigh → knee → lower leg → 4th toe.\\n\\n⚠️ **Exam Alert**: Lateral leg pain, IT band issues, lateral knee pain = GB meridian imbalance. Key points: GB-34 (lateral knee), GB-30 (hip).\\n\\n✅ **Why Correct**: The GB meridian pathway follows the entire lateral aspect of the leg. Understanding meridian pathways helps identify pain patterns and select appropriate acupressure treatment points for lateral leg issues."
    },
    {
        "qid": 172,
        "old": "The coracoid process is a hook-shaped bony projection of the scapula that extends anteriorly and laterally below the clavicle. It serves as an important attachment point for several muscles (pectoralis minor, coracobrachialis, short head of biceps brachii) and ligaments (coracoclavicular, coracoacromial). Located just below the lateral clavicle on the anterior shoulder, it's palpable in the deltopectoral groove. The coracoid process is considered an endangerment site because neurovascular structures (brachial plexus nerves, axillary artery) pass nearby. Deep pressure here risks nerve compression or vascular damage. Therapists must use caution when palpating this region.",
        "new": "🎯 **Key Concept**: The **coracoid process** is a hook-shaped bony projection of the scapula below the clavicle - an **ENDANGERMENT SITE** due to nearby neurovascular structures.\\n\\n💡 **Memory Tip**: CORACOID = CAUTION! Brachial plexus nerves and axillary artery pass nearby. Deep pressure = nerve compression or vascular damage risk!\\n\\n⚠️ **Exam Alert**: Located in deltopectoral groove, just below lateral clavicle on anterior shoulder. Palpable but requires gentle touch.\\n\\n✅ **Why Correct**: This hook-shaped projection serves as attachment for pec minor, coracobrachialis, short head of biceps, and ligaments (coracoclavicular, coracoacromial). Therapists must use caution when palpating this region to avoid neurovascular damage."
    },
    {
        "qid": 173,
        "old": "In Traditional Chinese Medicine, the Lungs (LU) are the Yin organ most associated with dryness. The Lungs control the skin and body hair, govern respiration, and manage body fluids' distribution to the skin surface. When Lung qi is deficient or imbalanced, it manifests as dryness: dry skin, dry cough, dry throat, or difficulty moistening tissues. The Lungs are particularly vulnerable to dryness (especially in autumn, their associated season). They're also affected by dry climates or heating systems. Treatment focuses on nourishing Lung yin, using moistening foods, humidifying air, and acupressure on Lung meridian points to restore moisture balance.",
        "new": "🎯 **Key Concept**: In TCM, **Lungs (LU)** are the Yin organ most associated with **DRYNESS**. Lungs control skin, body hair, and fluid distribution to skin surface.\\n\\n💡 **Memory Tip**: LUNGS = LACKING moisture! Dry skin, dry cough, dry throat = Lung qi deficiency. Lungs distribute fluids to skin - when weak, everything dries out!\\n\\n⚠️ **Exam Alert**: Lungs are vulnerable to dryness in autumn (their associated season) and from dry climates/heating systems.\\n\\n✅ **Why Correct**: When Lung qi is deficient/imbalanced, it manifests as dryness throughout the body. Treatment nourishes Lung yin using moistening foods, humidifying air, and acupressure on Lung meridian points to restore moisture balance."
    },
    {
        "qid": 174,
        "old": "The rotator cuff consists of four small muscles that stabilize the shoulder: Supraspinatus, Infraspinatus, Teres minor, and Subscapularis (SITS). These muscles form a 'cuff' around the humeral head, providing dynamic stability during arm movements. Supraspinatus initiates abduction, Infraspinatus and Teres minor externally rotate, Subscapularis internally rotates. Rotator cuff tears commonly occur from repetitive overhead activities, falls, or aging degeneration. Symptoms include shoulder pain, weakness, and limited range of motion. Massage therapy can help surrounding muscles but cannot repair tears - surgical intervention may be needed for complete tears. Understanding rotator cuff anatomy is essential for shoulder assessment.",
        "new": "🎯 **Key Concept**: The **rotator cuff = SITS muscles** - **S**upraspinatus, **I**nfraspinatus, **T**eres minor, **S**ubscapularis - forming a stabilizing 'cuff' around the humeral head.\\n\\n💡 **Memory Tip**: The shoulder SITS on these four! SITS muscles = dynamic shoulder stability during arm movements.\\n\\n⚠️ **Exam Alert**: Supraspinatus = initiates abduction, Infraspinatus + Teres minor = external rotation, Subscapularis = internal rotation.\\n\\n✅ **Why Correct**: Rotator cuff tears occur from repetitive overhead activities, falls, or aging degeneration. Symptoms: shoulder pain, weakness, limited ROM. Massage helps surrounding muscles but cannot repair tears - complete tears may need surgery."
    },
    {
        "qid": 175,
        "old": "The wrist (radiocarpal joint) allows four primary movements: flexion/extension (sagittal plane) and abduction/adduction (frontal plane). Wrist abduction (radial deviation) moves the hand toward the thumb side, while adduction (ulnar deviation) moves it toward the pinky side. These lateral movements occur in the frontal plane and are essential for functional hand positioning. Understanding wrist movements helps therapists assess range of motion limitations, identify muscle imbalances, and design effective treatment strategies. Flexion and extension occur in the sagittal plane. The wrist's ball-and-socket-like movements result from combined radiocarpal and midcarpal joint actions.",
        "new": "🎯 **Key Concept**: The wrist allows four movements: **flexion/extension (sagittal plane)** and **abduction/adduction (frontal plane)**. Abduction = toward thumb, Adduction = toward pinky.\\n\\n💡 **Memory Tip**: WRIST WAVES! Flexion/extension = forward/back waves. Abduction/adduction = side-to-side waves (thumb side vs pinky side).\\n\\n⚠️ **Exam Alert**: Abduction = radial deviation (toward radius/thumb). Adduction = ulnar deviation (toward ulna/pinky). These are FRONTAL plane movements.\\n\\n✅ **Why Correct**: These lateral movements are essential for functional hand positioning. Understanding wrist movements helps assess ROM limitations, identify muscle imbalances, and design treatment strategies. The wrist's movements result from combined radiocarpal and midcarpal joint actions."
    },
    {
        "qid": 176,
        "old": "The tensor fasciae latae (TFL) is the primary muscle that attaches to the iliotibial band (ITB). The TFL originates from the anterior superior iliac spine (ASIS) and inserts into the ITB, which then continues down the lateral thigh to attach at the lateral tibial condyle (Gerdy's tubercle). The TFL works synergistically with the gluteus maximus (which also attaches to the ITB) to stabilize the hip and knee. Tight TFL contributes to ITB syndrome, causing lateral knee pain. The TFL assists with hip flexion, abduction, and internal rotation. Understanding this connection is crucial for treating ITB-related conditions and lateral hip/knee pain.",
        "new": "🎯 **Key Concept**: The **tensor fasciae latae (TFL)** is the primary muscle attaching to the **iliotibial band (ITB)**. TFL originates from ASIS → inserts into ITB → ITB continues to lateral tibia.\\n\\n💡 **Memory Tip**: TFL = TENSES the IT Band! Like a TENSOR pulling on a rubber band - TFL pulls the ITB tight from hip to knee.\\n\\n⚠️ **Exam Alert**: Tight TFL → ITB syndrome → lateral knee pain. TFL works with gluteus maximus (also attaches to ITB) to stabilize hip and knee.\\n\\n✅ **Why Correct**: TFL assists with hip flexion, abduction, and internal rotation. Understanding this TFL→ITB connection is crucial for treating ITB syndrome and lateral hip/knee pain. The ITB runs from ASIS down lateral thigh to Gerdy's tubercle (lateral tibial condyle)."
    },
    {
        "qid": 177,
        "old": "Piriformis syndrome occurs when the piriformis muscle compresses the sciatic nerve. The piriformis is a deep hip rotator that lies beneath the gluteal muscles, running from the sacrum to the greater trochanter of the femur. The sciatic nerve typically passes beneath (sometimes through) the piriformis. When the piriformis becomes tight or inflamed, it can compress the sciatic nerve, causing pain, numbness, and tingling down the leg (sciatica symptoms). This differs from disc-related sciatica. Treatment includes stretching the piriformis, releasing trigger points, and addressing hip muscle imbalances. The piriformis test helps diagnose this condition through passive internal hip rotation.",
        "new": "🎯 **Key Concept**: **Piriformis syndrome** = piriformis muscle compressing the **sciatic nerve**, causing pain, numbness, tingling down the leg (sciatica symptoms).\\n\\n💡 **Memory Tip**: PIRI-FORMIS sits on SCIATIC nerve! Deep hip rotator (sacrum → greater trochanter) SQUEEZES nerve beneath it when tight/inflamed.\\n\\n⚠️ **Exam Alert**: This differs from disc-related sciatica. Sciatic nerve passes beneath (sometimes through) the piriformis. Piriformis test uses passive internal hip rotation to diagnose.\\n\\n✅ **Why Correct**: The piriformis is a deep hip rotator beneath gluteal muscles. When tight/inflamed, it compresses the sciatic nerve. Treatment: stretching piriformis, releasing trigger points, addressing hip muscle imbalances."
    },
    {
        "qid": 178,
        "old": "Petrissage is a massage technique involving rhythmic lifting, squeezing, rolling, and kneading of soft tissues. The key characteristic is the vertical lifting of tissue away from underlying structures, distinguishing it from gliding techniques like effleurage. Petrissage increases circulation, stretches muscle fibers, breaks up adhesions, and helps remove metabolic waste. The alternating compression and release creates a pumping action that enhances blood flow and lymphatic drainage. Common petrissage techniques include kneading, picking up, wringing, and rolling. This technique is particularly effective for addressing muscle tension and improving tissue mobility.",
        "new": "🎯 **Key Concept**: **Petrissage** = rhythmic **lifting, squeezing, rolling, kneading** of soft tissues. Key characteristic: **VERTICAL lifting** away from underlying structures.\\n\\n💡 **Memory Tip**: PETRISSAGE = PET the TISSUES! Like kneading dough - LIFT, squeeze, roll, knead. Not gliding (effleurage) - LIFTING!\\n\\n⚠️ **Exam Alert**: Common techniques: kneading, picking up, wringing, rolling. Distinguishes from gliding techniques like effleurage.\\n\\n✅ **Why Correct**: Petrissage increases circulation, stretches muscle fibers, breaks up adhesions, removes metabolic waste. The alternating compression/release creates pumping action enhancing blood flow and lymphatic drainage. Particularly effective for muscle tension and tissue mobility."
    },
    {
        "qid": 179,
        "old": "Effleurage consists of smooth, gliding strokes that follow the contours of the body, typically performed in the direction of venous and lymphatic flow (toward the heart). The primary purposes are: warming tissues to prepare for deeper work, assessing tissue condition, promoting relaxation, enhancing circulation, and facilitating lymphatic drainage. Effleurage can be light (superficial) or deep, using palms, fingers, or forearms. It's typically the opening and closing technique in massage sessions. The continuous contact and rhythmic nature promote parasympathetic nervous system activation, inducing relaxation. Effleurage is versatile, safe, and foundational to most massage modalities.",
        "new": "🎯 **Key Concept**: **Effleurage** = smooth, **gliding strokes** following body contours, typically toward the heart (direction of venous/lymphatic flow).\\n\\n💡 **Memory Tip**: EFFLEURAGE = EASY FLOW! Gliding strokes that FLOW smoothly - warming, assessing, relaxing, circulating. Opening and closing technique!\\n\\n⚠️ **Exam Alert**: Can be light (superficial) or deep. Uses palms, fingers, or forearms. Continuous contact and rhythm activate parasympathetic nervous system.\\n\\n✅ **Why Correct**: Primary purposes: warm tissues for deeper work, assess tissue condition, promote relaxation, enhance circulation, facilitate lymphatic drainage. Versatile, safe, and foundational to most massage modalities."
    },
    {
        "qid": 180,
        "old": "Tapotement consists of rhythmic percussive movements including cupping, hacking, pounding, and tapping. In pre-event massage, tapotement is valuable because it stimulates the nervous system, increases alertness, and prepares muscles for activity. The rapid, rhythmic percussion activates mechanoreceptors and stimulates nerve pathways, creating an energizing effect. This technique increases circulation and muscle tone, making it ideal for athletes before competition. Tapotement's stimulating nature contrasts with relaxation techniques. It's brief and invigorating, helping transition from rest to activity. However, tapotement should be avoided in relaxation massage or with clients who have inflammation or fragile tissues.",
        "new": "🎯 **Key Concept**: **Tapotement** = rhythmic **percussive movements** (cupping, hacking, pounding, tapping). For **pre-event massage** - stimulates nervous system, increases alertness, prepares muscles for activity.\\n\\n💡 **Memory Tip**: TAP to ACTIVATE! Rapid percussion = energizing effect. Like tapping someone awake - stimulates nerves, increases circulation and muscle tone.\\n\\n⚠️ **Exam Alert**: AVOID in relaxation massage or with inflammation/fragile tissues. Brief and invigorating - helps transition from rest to activity.\\n\\n✅ **Why Correct**: Rapid, rhythmic percussion activates mechanoreceptors and stimulates nerve pathways, creating energizing effect ideal for athletes before competition. Contrasts with relaxation techniques - this is stimulating, not calming."
    },
    {
        "qid": 181,
        "old": "Muscle cramps are involuntary, sustained muscle contractions often caused by electrolyte imbalances, fatigue, or dehydration. The gastrocnemius, being a powerful calf muscle heavily used in running, is particularly prone to cramping. Compression is the most effective immediate treatment because it provides direct pressure that helps interrupt the abnormal nerve firing pattern causing the spasm. The pressure stimulates mechanoreceptors which can help reset the muscle's neuromuscular control. This should be combined with gentle lengthening once the acute spasm subsides. Compression is safe, immediate, and doesn't risk further tissue damage.",
        "new": "🎯 **Key Concept**: For gastrocnemius cramps, use **COMPRESSION** - direct pressure that interrupts abnormal nerve firing and resets neuromuscular control.\\n\\n💡 **Memory Tip**: CRAMP needs COMPRESSION! SQUEEZE the SPASM to make it STOP! Direct pressure resets the muscle's electrical activity.\\n\\n⚠️ **Exam Alert**: AVOID aggressive stretching (can tear fibers during spasm), trigger point work (too intense), or friction (can aggravate spasm).\\n\\n✅ **Why Correct**: Cramps = involuntary, sustained contractions (from electrolytes, fatigue, dehydration). Compression stimulates mechanoreceptors, breaking the cramp cycle. Safe, immediate, doesn't risk tissue damage. Combine with gentle lengthening AFTER spasm subsides."
    },
    {
        "qid": 182,
        "old": "SP-6 (Sanyinjiao or Three Yin Crossing) is the crucial acupoint where the three Yin meridians of the leg converge: Spleen, Liver, and Kidney meridians. Located about 3 finger-widths above the medial malleolus, behind the tibia, this point is considered one of the most important in acupuncture and acupressure. It's used to treat gynecological issues, digestive problems, insomnia, and emotional imbalances because it affects all three Yin organ systems simultaneously. The convergence makes it a powerful harmonizing point that balances the body's Yin energy, making it essential knowledge for massage therapists incorporating Traditional Chinese Medicine principles.",
        "new": "🎯 **Key Concept**: **SP-6 (Sanyinjiao/Three Yin Crossing)** = convergence point where **Spleen, Liver, and Kidney meridians** meet (3 finger-widths above medial malleolus, behind tibia).\\n\\n💡 **Memory Tip**: SP-6 is where the three Yin ladies meet for SIX o'clock tea! Spleen, Liver, and Kidney all Sip tea at SP-6!\\n\\n⚠️ **Exam Alert**: One of the MOST IMPORTANT points in acupuncture/acupressure. Affects all three Yin organ systems simultaneously.\\n\\n✅ **Why Correct**: Used for gynecological issues, digestive problems, insomnia, emotional imbalances. The convergence makes it a powerful harmonizing point that balances the body's Yin energy - essential for massage therapists using TCM principles."
    },
    {
        "qid": 183,
        "old": "Professional scope of practice requires massage therapists to work around any unidentified lumps or masses and immediately inform the client while recommending medical evaluation. This protects both client safety and therapist liability. Massage therapists are not qualified to diagnose masses, and applying pressure to unknown growths could potentially be harmful if they are malignant or contain fluid. The ethical approach involves: avoiding the area entirely, professionally communicating the finding to the client without causing alarm, documenting the discovery, and suggesting medical consultation. This demonstrates professional boundaries and prioritizes client welfare over completing the massage session.",
        "new": "🎯 **Key Concept**: When finding an unidentified lump, **work AROUND it, inform the client, and recommend medical evaluation**. NEVER work directly on unknown masses.\\n\\n💡 **Memory Tip**: When in doubt, CARE: **C**ommunicate, **A**void the area, **R**efer out, **E**ducate the client! Never work ON mysterious lumps!\\n\\n⚠️ **Exam Alert**: Massage therapists are NOT qualified to diagnose masses. Applying pressure could be harmful if malignant or fluid-filled.\\n\\n✅ **Why Correct**: Ethical approach: avoid area entirely, professionally communicate finding without alarm, document discovery, suggest medical consultation. Demonstrates professional boundaries and prioritizes client welfare over completing the session."
    },
    {
        "qid": 184,
        "old": "Massage therapy's primary physiologically proven benefit is enhanced circulation through mechanical pressure and movement. The manipulation of soft tissues promotes venous return, lymphatic drainage, and capillary blood flow. This increased circulation delivers oxygen and nutrients while removing metabolic waste products. While massage has many benefits, claims about cellulite reduction, weight loss, or increased muscle power lack scientific evidence. Circulation improvement is measurable and documented, making it the most accurate therapeutic claim. This enhanced blood flow also supports tissue healing, reduces inflammation, and promotes relaxation through improved nutrient delivery.",
        "new": "🎯 **Key Concept**: Massage's **primary proven benefit** is **enhanced circulation** - promoting venous return, lymphatic drainage, and capillary blood flow.\\n\\n💡 **Memory Tip**: Massage Makes Blood Move! Circulation is the core scientifically proven benefit - measurable and documented.\\n\\n⚠️ **Exam Alert**: Claims about cellulite reduction, weight loss, or increased muscle power LACK scientific evidence. Don't make unsupported claims!\\n\\n✅ **Why Correct**: Mechanical pressure and movement deliver oxygen/nutrients while removing metabolic waste. This enhanced blood flow supports tissue healing, reduces inflammation, and promotes relaxation through improved nutrient delivery."
    },
    {
        "qid": 185,
        "old": "The liver is primarily located in the lower right abdominal quadrant, though it's actually the largest organ and extends across multiple quadrants. The abdominal cavity is divided into four quadrants by imaginary lines through the umbilicus. The liver's bulk sits in the lower right quadrant beneath the right costal margin. This large organ performs over 500 functions including detoxification, protein synthesis, and bile production. Knowledge of liver location is crucial for massage therapists to avoid deep pressure in this area and recognize potential referred pain patterns. The liver's size and position make it vulnerable to trauma from excessive abdominal pressure.",
        "new": "🎯 **Key Concept**: The liver is primarily located in the **LOWER RIGHT abdominal quadrant**, though it extends across multiple quadrants as the body's largest organ.\\n\\n💡 **Memory Tip**: Liver Lives in Lower Right - like a heavy liver sinking down to the bottom right corner!\\n\\n⚠️ **Exam Alert**: The liver performs over 500 functions (detoxification, protein synthesis, bile production). Vulnerable to trauma from excessive abdominal pressure.\\n\\n✅ **Why Correct**: The liver's bulk sits beneath the right costal margin in the lower right quadrant (divided by imaginary lines through umbilicus). Knowledge crucial for massage therapists to avoid deep pressure and recognize referred pain patterns."
    },
    {
        "qid": 186,
        "old": "The pancreas is the endocrine gland directly associated with diabetes through its production of insulin and glucagon. Located behind the stomach, the pancreas contains specialized beta cells in the islets of Langerhans that secrete insulin to regulate blood glucose levels. In Type 1 diabetes, these cells are destroyed by autoimmune processes. In Type 2 diabetes, cells become resistant to insulin or the pancreas doesn't produce enough. This organ has both endocrine (hormone-producing) and exocrine (digestive enzyme) functions. For massage therapists, understanding diabetes is crucial as diabetic clients may have circulation issues, slower healing, and neuropathy requiring modified pressure and techniques.",
        "new": "🎯 **Key Concept**: The **pancreas** is the endocrine gland associated with diabetes - it produces **insulin and glucagon** to regulate blood glucose.\\n\\n💡 **Memory Tip**: Pancreas Produces Insulin - when it fails, sugar Problems Increase! Beta cells in islets of Langerhans make insulin.\\n\\n⚠️ **Exam Alert**: Type 1 = beta cells destroyed (autoimmune). Type 2 = insulin resistance or insufficient production. Pancreas has endocrine AND exocrine functions.\\n\\n✅ **Why Correct**: Located behind stomach. For massage therapists: diabetic clients may have circulation issues, slower healing, and neuropathy requiring modified pressure and techniques."
    },
    {
        "qid": 187,
        "old": "The adrenal glands are small, triangular endocrine glands positioned directly above (superior to) each kidney, like caps sitting on top. They're also called suprarenal glands ('supra' = above, 'renal' = kidney). Each adrenal has two parts: the outer cortex produces cortisol and aldosterone, while the inner medulla produces adrenaline and noradrenaline. This superior positioning allows them to receive rich blood supply and quickly release stress hormones into circulation. The anatomical relationship is crucial for surgical procedures and understanding hormone regulation during stress responses.",
        "new": "🎯 **Key Concept**: Adrenal glands are positioned **SUPERIOR (above)** to each kidney - like caps sitting on top. Also called **suprarenal** glands ('supra' = above).\\n\\n💡 **Memory Tip**: Adrenals sit on top like CAPS - 'Caps Always Positioned Superior!' The adrenals are literally caps on the kidneys.\\n\\n⚠️ **Exam Alert**: Each adrenal has two parts: outer cortex (cortisol, aldosterone) and inner medulla (adrenaline, noradrenaline). Triangular shape.\\n\\n✅ **Why Correct**: Superior positioning allows rich blood supply and quick stress hormone release into circulation. The anatomical relationship is crucial for understanding hormone regulation during stress responses."
    },
    {
        "qid": 188,
        "old": "In Traditional Chinese Medicine, the Liver meridian (LR) runs along the lateral (outer) side of the big toe, specifically at point LR1 (Dadun). The Liver meridian pathway begins at the lateral nail bed of the big toe and travels up the medial leg to the torso. This meridian governs emotional regulation, detoxification, and smooth qi flow. LR1 is used clinically for issues like insomnia, anxiety, and menstrual irregularities. Understanding meridian pathways is essential for acupressure and energy work in massage therapy, helping therapists apply appropriate pressure points for therapeutic effect.",
        "new": "🎯 **Key Concept**: The **Liver meridian (LR)** runs along the **LATERAL (outer) side of the big toe** at point LR1 (Dadun), then travels up the medial leg.\\n\\n💡 **Memory Tip**: Lateral big toe = LR (Liver) - 'Liver Runs along the big toe's outside edge.' Your Liver needs to 'step Right' (lateral) to detox!\\n\\n⚠️ **Exam Alert**: SP (Spleen) runs along MEDIAL (inner) side of big toe. KI (Kidney) originates from sole of foot, not big toe.\\n\\n✅ **Why Correct**: Liver meridian begins at lateral nail bed of big toe, travels up medial leg to torso. Governs emotional regulation, detoxification, smooth qi flow. LR1 used for insomnia, anxiety, menstrual irregularities."
    },
    {
        "qid": 189,
        "old": "Professional misconduct in massage therapy includes failing to maintain proper client records as required by state law. In New York, massage therapists must keep detailed treatment records for each client, including intake information, treatment plans, progress notes, and session documentation. These records protect both client safety and therapist liability, provide continuity of care, demonstrate professional standards, and comply with legal requirements. Records must typically be retained for several years and kept confidential. Failure to maintain proper documentation can result in license suspension, fines, or revocation, as it violates professional standards and regulatory requirements.",
        "new": "🎯 **Key Concept**: **Professional misconduct** = failing to maintain proper client records (required by NY state law). Therapists MUST keep detailed treatment records.\\n\\n💡 **Memory Tip**: No Records = No License! 'Keep Every Client's Story' - failing to document risks your career.\\n\\n⚠️ **Exam Alert**: Required records: intake info, treatment plans, progress notes, session documentation. Retained for several years. Must be kept CONFIDENTIAL.\\n\\n✅ **Why Correct**: Records protect client safety and therapist liability, provide continuity of care, demonstrate professional standards, and comply with legal requirements. Failure can result in license suspension, fines, or revocation."
    },
    {
        "qid": 190,
        "old": "In healthcare documentation, information is classified as subjective or objective. Subjective data includes anything the client reports about their own experience - symptoms, pain levels, medical history, lifestyle factors, goals, and concerns. This is information that cannot be independently verified by the therapist and comes directly from the client's perspective ('subject'). It's typically documented as 'chief complaint' or patient history. Subjective data guides treatment planning but must be balanced with objective findings. Understanding this distinction helps therapists properly document sessions and communicate with other healthcare providers using standardized medical terminology.",
        "new": "🎯 **Key Concept**: Client's intake form input is **SUBJECTIVE data** - information the client reports about their own experience that cannot be independently verified.\\n\\n💡 **Memory Tip**: Client Says = Subjective! 'Subject tells their story' - pain levels, symptoms, history, goals, concerns all come from client's perspective.\\n\\n⚠️ **Exam Alert**: OBJECTIVE data = therapist's measurable observations (ROM, swelling, temperature). ASSESSMENT = therapist's professional analysis combining both.\\n\\n✅ **Why Correct**: Subjective data typically documented as 'chief complaint' or patient history. Guides treatment planning but must be balanced with objective findings. This distinction helps properly document sessions and communicate with healthcare providers."
    },
    {
        "qid": 191,
        "old": "Abdominal vibration for constipation works by stimulating the nervous system and promoting digestive function. The technique stimulates (not fatigues) nerves, particularly the parasympathetic nerves that control digestion. It promotes tissue fluid movement by creating mechanical oscillations that enhance lymphatic drainage and blood flow. Vibration also induces peristaltic action by mechanically stimulating intestinal smooth muscle contractions that move waste through the colon. The goal is activation and stimulation of normal digestive processes. Fatiguing nerves would be counterproductive, as it would decrease nerve function and potentially worsen constipation by reducing the neural drive needed for proper bowel function.",
        "new": "🎯 **Key Concept**: Abdominal vibration for constipation **STIMULATES nerves** (parasympathetic), promotes fluid movement, and induces peristalsis. It does NOT fatigue nerves.\\n\\n💡 **Memory Tip**: Vibration ENERGIZES, never fatigues! Think 'Wake Up the gut, don't tire it out!' - therapeutic vibration ACTIVATES.\\n\\n⚠️ **Exam Alert**: Fatiguing nerves would DECREASE function and WORSEN constipation by reducing neural drive for bowel function. The OPPOSITE of therapeutic goal!\\n\\n✅ **Why Correct**: Vibration stimulates parasympathetic nerves (control digestion), creates mechanical oscillations (enhance lymphatic drainage/blood flow), and mechanically stimulates intestinal smooth muscle (moves waste through colon). Goal is ACTIVATION of digestive processes."
    },
    {
        "qid": 192,
        "old": "Client confidentiality is protected by HIPAA and state privacy laws. Massage therapists must obtain explicit written consent before releasing any client information, including progress notes, to other healthcare providers. Even when providers are collaborating on treatment, client authorization is legally required. This protects client privacy rights and prevents unauthorized disclosure. The therapist should request signed release forms specifying what information can be shared and with whom before providing any documentation.",
        "new": "🎯 **Key Concept**: **Get CLIENT CONSENT before releasing progress notes** to chiropractor (or any provider). Written authorization is legally required by HIPAA and state privacy laws.\\n\\n💡 **Memory Tip**: CONSENT before you CONTENT - Never share client records without written permission first!\\n\\n⚠️ **Exam Alert**: Even when providers collaborate on treatment, client authorization is STILL legally required. Protects privacy rights and prevents unauthorized disclosure.\\n\\n✅ **Why Correct**: Request signed release forms specifying WHAT information can be shared and WITH WHOM before providing any documentation. Direct sharing without consent violates HIPAA and professional ethics."
    },
])

# Process all conversions
converted_count = 0
for item in conversions:
    qid = item["qid"]
    old_text = item["old"]
    new_text = item["new"]

    if old_text in content:
        content = content.replace(old_text, new_text)
        print(f"[OK] Converted question {qid}")
        converted_count += 1
    else:
        print(f"[SKIP] Could not find question {qid}")

# Write back
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\\nConversion complete! {converted_count}/{len(conversions)} questions updated.")
print("Questions 149-192 have been converted to beautiful markdown format!")
