#!/usr/bin/env python3
"""
Convert topic_explanation fields for questions 145-192 to markdown format.
"""

import re
import json

# Read the file
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# Define conversions for each question
conversions = {
    145: {
        "old": "To palpate the right SCM, rotate the head to the left side. This position puts the right SCM into contraction and makes it prominent and easily palpable. The SCM has dual origins (sternum and clavicle) and inserts on the mastoid process. When one SCM contracts, it rotates the head to the opposite side while side-bending to the same side. This opposite rotation principle is key for muscle palpation - you want to position the muscle in slight tension to make it stand out from surrounding tissues. Understanding SCM positioning is crucial for massage therapists treating neck tension and torticollis.",
        "new": "🎯 **Key Concept**: To palpate the right SCM, rotate the head to the LEFT side. This opposite rotation puts the muscle into contraction, making it prominent and easily palpable.\\n\\n💡 **Memory Tip**: Turn head AWAY to make it STAY! Right SCM pops out when head turns LEFT.\\n\\n⚠️ **Exam Alert**: The SCM has dual origins (sternum and clavicle) and inserts on the mastoid process. When one SCM contracts, it rotates the head to the opposite side.\\n\\n✅ **Why Correct**: This opposite rotation principle is key for muscle palpation - you want the muscle in slight tension to make it stand out. Understanding SCM positioning is crucial for treating neck tension and torticollis."
    },
    146: {
        "old": "Distributing business cards to strangers in everyday public situations like supermarket lines constitutes unprofessional solicitation and may violate professional boundaries. This approach can make people uncomfortable and reflects poorly on the massage therapy profession. Professional marketing should occur through appropriate channels: legitimate advertising, referral networks, professional events, and established business relationships. Raffles, TV advertising, and gift certificates for existing clients are all acceptable marketing strategies when conducted ethically and within regulatory guidelines. Understanding professional boundaries in client acquisition is essential for maintaining licensure and professional reputation.",
        "new": "🎯 **Key Concept**: Passing out business cards to strangers in public places like supermarket lines is **unprofessional solicitation** that violates professional boundaries.\\n\\n💡 **Memory Tip**: Don't be a PEST! Pestering people in Public Everyday Situations = unprofessional marketing.\\n\\n⚠️ **Exam Alert**: Professional marketing includes raffles, TV ads, and gift certificates for existing clients - all acceptable when done ethically.\\n\\n✅ **Why Correct**: Professional marketing should occur through appropriate channels: legitimate advertising, referral networks, and professional events - NOT random solicitation that makes people uncomfortable."
    },
    147: {
        "old": "Body membranes are thin sheets of tissue that cover surfaces, line cavities, and separate organs. The three main types are: Serous membranes (line closed cavities like pleura, pericardium), Mucous membranes (line body openings like respiratory/digestive tracts), and Synovial membranes (line joint cavities, produce synovial fluid). Fibrous tissue refers to connective tissue containing collagen fibers, not a membrane type. Remember: membranes are specialized epithelial tissues that line or cover, while fibrous tissue provides structural support.",
        "new": "🎯 **Key Concept**: The three membrane types are **Serous** (line closed cavities), **Mucous** (line body openings), and **Synovial** (line joints). Fibrous tissue is NOT a membrane - it's connective tissue.\\n\\n💡 **Memory Tip**: SMS - **S**erous, **M**ucous, **S**ynovial are the membrane trio! Fibrous is just tissue, not membrane to go!\\n\\n⚠️ **Exam Alert**: Don't confuse fibrous connective tissue with actual membrane types. Membranes are specialized epithelial tissues that line or cover.\\n\\n✅ **Why Correct**: Fibrous tissue provides structural support through collagen fibers - it's not a specialized membrane that lines cavities or produces secretions."
    },
    148: {
        "old": "Joint dislocation triggers an immediate inflammatory response as the body recognizes tissue damage and potential infection risk. White blood cells proliferate and rush to the injury site within minutes to prevent infection and begin healing. This inflammatory cascade includes vasodilation, increased vascular permeability, and immune cell recruitment. While muscle spasm may occur later as a protective mechanism, and fascial restrictions develop over time, the body's most immediate priority is deploying immune defenses through white blood cell activation and proliferation.",
        "new": "🎯 **Key Concept**: Joint dislocation triggers **immediate white blood cell proliferation** - the body's first-response inflammatory defense system that rushes to the injury within minutes.\\n\\n💡 **Memory Tip**: WBC Rush - When Bones Come apart, White Blood Cells RUSH to the rescue immediately!\\n\\n⚠️ **Exam Alert**: Muscle spasm occurs later as secondary protection. Fascial restrictions develop over time. WBC response is the IMMEDIATE reaction.\\n\\n✅ **Why Correct**: The inflammatory cascade (vasodilation, increased vascular permeability, immune cell recruitment) is the body's most immediate priority to prevent infection and begin healing."
    },
    149: {
        "old": "The skin has four primary functions: protection (barrier against pathogens, UV radiation, physical damage), heat regulation (sweating, vasodilation/vasoconstriction), sensation (touch, pressure, temperature, pain receptors), and absorption. While the skin does have some absorptive capacity, especially for lipid-soluble substances, this is the least significant function compared to the others. The skin is primarily designed as a barrier rather than an absorptive organ - most substances cannot penetrate the outer epidermal layers. Protection, thermoregulation, and sensation are vital survival functions that the body prioritizes over absorption.",
        "new": "🎯 **Key Concept**: Skin's main functions are **P**rotection, **H**eat regulation, and **S**ensation. Absorption is the LEAST important - skin is a barrier, not designed for absorption.\\n\\n💡 **Memory Tip**: PHS - Protection, Heat regulation, Sensation are the skin's main mission! Absorption is limited - not the skin's best transmission!\\n\\n⚠️ **Exam Alert**: While skin has some absorptive capacity for lipid-soluble substances, it's designed as a BARRIER. Most substances can't penetrate the epidermis.\\n\\n✅ **Why Correct**: Protection, thermoregulation, and sensation are vital survival functions. Absorption is minimal and least significant compared to these critical protective roles."
    },
    150: {
        "old": "Heat application to a migraine sufferer is contraindicated because it causes vasodilation (blood vessel expansion), which can worsen the throbbing pain characteristic of migraines. Migraines involve already inflamed, dilated blood vessels in the brain. Adding heat would exacerbate this condition. Cold therapy is appropriate as it causes vasoconstriction, reducing blood flow and inflammation. Foot and hand work using reflexology principles is excellent for migraines, providing systemic relaxation without disturbing the sensitive head area.",
        "new": "🎯 **Key Concept**: Heat packs to the head are **CONTRAINDICATED** for migraines. Heat causes vasodilation (blood vessel expansion), worsening the throbbing pain from already inflamed, dilated vessels.\\n\\n💡 **Memory Tip**: Cool Head Hot Feet - Migraines need COOL on the head, never heat! Heat makes blood vessels expand and pain compete!\\n\\n⚠️ **Exam Alert**: Cold packs cause vasoconstriction (reducing inflammation). Foot and hand work using reflexology is excellent for migraines.\\n\\n✅ **Why Correct**: Migraines involve inflamed, dilated brain blood vessels. Adding heat exacerbates this condition. Cold therapy and reflexology work provide relief without aggravating the sensitive head area."
    },
    151: {
        "old": "Numbness indicates compromised nerve function, requiring gentle, non-invasive techniques. Effleurage uses light to moderate gliding strokes that gently stimulate circulation and nerve pathways without causing further damage. The gentle, rhythmic nature of effleurage can help 'wake up' dulled sensory nerves while being safe for compromised tissue. Aggressive techniques like trigger point work, tapotement (percussion), or deep friction could further traumatize already damaged or compressed nerves, potentially worsening the neuropathy. The goal is gentle stimulation to encourage nerve healing, not forceful intervention that might cause additional harm.",
        "new": "🎯 **Key Concept**: Numbness indicates compromised nerve function requiring **gentle effleurage** - light gliding strokes that safely stimulate circulation and nerve pathways without causing further damage.\\n\\n💡 **Memory Tip**: Numb Needs Nice - When sensation is gone, use EFFLEURAGE gentle and long! Light touch awakens nerves without alarm!\\n\\n⚠️ **Exam Alert**: Avoid aggressive techniques! Trigger point, tapotement (percussion), and deep friction could traumatize already damaged nerves and worsen neuropathy.\\n\\n✅ **Why Correct**: The gentle, rhythmic nature of effleurage can help 'wake up' dulled sensory nerves while being safe for compromised tissue. Goal is gentle stimulation for healing, not forceful intervention."
    },
    152: {
        "old": "HIV-positive clients with easy bruising, neuralgia, and circulation concerns require extremely gentle, non-invasive approaches. Polarity therapy works with energy fields without direct tissue manipulation, making it safe for immunocompromised clients with fragile capillaries. Direct massage techniques like effleurage, friction, and tapotement all risk causing bruising, tissue damage, and potential infection in HIV clients whose immune systems are compromised and healing ability is reduced. The combination of symptoms (easy bruising, nerve pain, poor circulation) indicates severely compromised tissue integrity that requires hands-off energy work rather than traditional manual manipulation.",
        "new": "🎯 **Key Concept**: HIV clients with easy bruising, neuralgia, and circulation concerns need **polarity therapy** - energy work WITHOUT direct tissue manipulation, protecting fragile capillaries and compromised immune systems.\\n\\n💡 **Memory Tip**: PALE HIV clients need Polarity: **P**-ale skin (bruises), **A**-che (neuralgia), **L**-eg circulation, **E**-nergy work. Direct touch techniques are too harsh!\\n\\n⚠️ **Exam Alert**: Effleurage, friction, and tapotement all risk bruising, tissue damage, and infection in immunocompromised clients with reduced healing ability.\\n\\n✅ **Why Correct**: The combination of symptoms indicates severely compromised tissue integrity requiring hands-off energy work rather than traditional manual manipulation that could cause harm."
    },
    153: {
        "old": "In Traditional Chinese Medicine (TCM), each organ system governs specific body parts and tissues. The Liver meridian controls the eyes and vision. Conjunctivitis (eye inflammation/redness) indicates Liver heat or Liver fire rising. This connection reflects the TCM principle that internal organ imbalances manifest in external symptoms. When the Liver has excess heat (from stress, anger, poor diet), it rises upward and affects the eyes, causing redness, inflammation, and irritation. Treatment would focus on clearing Liver heat and calming Liver yang. Understanding these TCM organ-tissue relationships helps massage therapists who incorporate Eastern medicine approaches.",
        "new": "🎯 **Key Concept**: In Traditional Chinese Medicine, the **Liver meridian controls the eyes**. Conjunctivitis (eye inflammation/redness) indicates Liver heat or Liver fire rising.\\n\\n💡 **Memory Tip**: LIVER sees ALL! **L**-iver controls **L**-ight (vision), **I**-nflammation in eyes, **V**-ision problems, **E**-ye redness, **R**-age (liver emotion affects eyes). When liver is hot, eyes get red!\\n\\n⚠️ **Exam Alert**: Heart governs tongue/speech, Lung controls skin/breathing, Spleen governs digestion/muscle. Only Liver connects to eyes.\\n\\n✅ **Why Correct**: TCM principle: internal organ imbalances manifest externally. Excess Liver heat (from stress, anger, poor diet) rises upward and affects the eyes, causing inflammation. Treatment clears Liver heat."
    },
    154: {
        "old": "Pain radiating down the posterior leg with numbness is a classic presentation of sciatic nerve compression, most commonly caused by a herniated disc (specifically, herniated annulus fibrosus - the outer ring of the intervertebral disc). When the disc herniates, the nucleus pulposus (inner gel) pushes through the torn annulus fibrosus, compressing the nerve root. This causes both pain (from nerve irritation) and numbness (from nerve compression blocking sensory signals). Osgood-Schlatter's affects the knee in adolescents without leg radiation. Chondromalacia patella causes anterior knee pain, not posterior leg symptoms.",
        "new": "🎯 **Key Concept**: Pain radiating down posterior leg with numbness = **herniated annulus fibrosus** (disc herniation) compressing the sciatic nerve root.\\n\\n💡 **Memory Tip**: HERNIATED disc = RADIATED pain! **H**-erniated annulus, **E**-xtreme pain, **R**-adiation down leg, **N**-umbness follows, **I**-mpinged nerve, **A**-nnulus torn, **T**-ingling, **E**-verything shoots Down!\\n\\n⚠️ **Exam Alert**: Osgood-Schlatter's = localized knee pain in adolescents. Chondromalacia patella = anterior knee pain. Neither causes posterior leg radiation or numbness.\\n\\n✅ **Why Correct**: When the disc herniates, nucleus pulposus pushes through torn annulus fibrosus, compressing nerve root. This causes pain (nerve irritation) AND numbness (blocked sensory signals)."
    },
    155: {
        "old": "Trigger points are small, hyperirritable nodules within taut muscle bands. Finding them requires precise, focused palpation. Short gliding strokes allow the therapist to slowly and methodically scan muscle tissue, detecting subtle changes in texture and localized tenderness. These strokes are slow, deliberate, and cover small areas at a time. Deep petrissage (kneading) is too broad and forceful for precise detection. Effleurage uses long, flowing strokes that cover large areas and would miss small trigger points. Short gliding strokes provide the sensitivity and specificity needed to locate these tiny, specific pain generators.",
        "new": "🎯 **Key Concept**: Finding trigger points requires **short gliding strokes** - slow, deliberate scanning that detects subtle texture changes and localized tenderness in small areas.\\n\\n💡 **Memory Tip**: SHORT and SWEET finds the SPOT! Short Gliding = Spot Finding. Like a detective using SHORT steps to find clues - long strokes MISS tiny trigger points!\\n\\n⚠️ **Exam Alert**: Deep petrissage (kneading) is too broad and forceful. Effleurage uses long strokes that cover large areas and miss small nodules.\\n\\n✅ **Why Correct**: Trigger points are small, hyperirritable nodules within taut bands. Short gliding strokes provide the sensitivity and specificity needed to locate these tiny, specific pain generators."
    },
    156: {
        "old": "In TCM, dark circles under eyes and low back pain both indicate Kidney/Bladder (KI/BL) meridian deficiency. The Kidney governs the low back region and controls aging processes - dark circles reflect Kidney essence depletion. Low back ache is a primary Kidney meridian symptom. When these meridians are deficient (weak, depleted), you TONIFY to strengthen and support them. Tonification techniques include gentle, slow, deliberate pressure moving in the direction of meridian flow, using moxa heat, and holding acupoints. This builds up depleted energy. Dispersal would further weaken an already deficient system. Stomach/Spleen relate to digestion, not these symptoms.",
        "new": "🎯 **Key Concept**: Dark circles under eyes + low back ache = **Kidney/Bladder (KI/BL) deficiency**. Treatment: **TONIFY** to strengthen and build up depleted energy.\\n\\n💡 **Memory Tip**: BLADDER-KIDNEY need BOOST! **B**-ack pain, **L**-ow energy, dark circles = **A**-ging kidneys, **D**-ark circles, **D**-epletion, **E**-xhaustion, **R**-enal weakness. TONIFY what's weak!\\n\\n⚠️ **Exam Alert**: Dispersal would WEAKEN an already deficient system. Stomach/Spleen relate to digestion, not these symptoms.\\n\\n✅ **Why Correct**: Kidney governs low back and aging processes. Dark circles reflect Kidney essence depletion. Tonification (gentle, slow pressure with meridian flow, moxa heat, holding acupoints) builds energy."
    },
    157: {
        "old": "In Traditional Chinese Medicine, the Kidney meridian governs hearing and the ears. Bilateral hearing loss indicates Kidney meridian deficiency or imbalance. The Kidneys store essence (jing) which nourishes the brain and sensory organs, particularly hearing. As people age, Kidney essence naturally declines, which is why age-related hearing loss is common. The Kidney meridian pathway connects to the ears. Treatment would focus on tonifying Kidney qi and essence. Liver governs eyes/vision, Spleen governs muscles/digestion, and Heart governs tongue/speech - none control hearing.",
        "new": "🎯 **Key Concept**: In TCM, the **Kidney meridian governs hearing and the ears**. Bilateral hearing loss = Kidney meridian deficiency or imbalance.\\n\\n💡 **Memory Tip**: KIDNEY = KEY to hearing! **K**-idney **E**-ssence **Y**-ields hearing. Age-related hearing loss = Kidney essence decline with aging.\\n\\n⚠️ **Exam Alert**: Liver → eyes/vision, Spleen → muscles/digestion, Heart → tongue/speech. Only Kidney controls ears and hearing.\\n\\n✅ **Why Correct**: Kidneys store essence (jing) which nourishes the brain and sensory organs, particularly hearing. Kidney meridian pathway connects directly to the ears. Treatment tonifies Kidney qi and essence."
    },
    158: {
        "old": "CV-17 (Conception Vessel 17), also called Danzhong or 'Sea of Qi,' is located at the center of the chest on the sternum, level with the 4th intercostal space (between the nipples). This is one of the most important acupoints for emotional regulation, particularly for calming anxiety, relieving stress, and treating respiratory issues. It's called the 'Sea of Qi' because it regulates qi throughout the chest and affects the Heart and Lung meridians. CV-17 is commonly used for emotional release, panic attacks, and chest tightness. Its central chest location makes it easily accessible and powerful for affecting both physical and emotional well-being.",
        "new": "🎯 **Key Concept**: **CV-17** (Danzhong/'Sea of Qi') is located at the **center of the chest on the sternum**, level with the 4th intercostal space (between the nipples).\\n\\n💡 **Memory Tip**: CV-17 = Center of **V**-ital energy! 'Sea of Qi' at the chest's center controls breath, heart, and emotional release.\\n\\n⚠️ **Exam Alert**: This point affects both Heart and Lung meridians. Used for anxiety, stress relief, respiratory issues, panic attacks, and chest tightness.\\n\\n✅ **Why Correct**: Called 'Sea of Qi' because it regulates qi throughout the chest. Its central location makes it easily accessible and powerful for affecting both physical and emotional well-being."
    },
    159: {
        "old": "Cross-fiber friction is a specific massage technique where strokes are applied perpendicular (at 90-degree angles) to muscle fiber direction. This transverse application helps break up adhesions, separate adhered fibers, and realign scar tissue. By working across the grain of the muscle rather than with it, the therapist can address restrictions between individual fibers and fascial layers. This technique is particularly effective for treating tendinitis, chronic muscle tension, and scar tissue. It creates controlled microtrauma that stimulates healing and tissue remodeling. The perpendicular approach is what distinguishes cross-fiber friction from other techniques.",
        "new": "🎯 **Key Concept**: Cross-fiber friction strokes are applied **perpendicular (90-degree angles) to muscle fiber direction** - working across the grain, not with it.\\n\\n💡 **Memory Tip**: CROSS the fibers = 90-degree CROSSING! Like rubbing across the wood grain, not with it, to smooth out rough spots.\\n\\n⚠️ **Exam Alert**: This technique breaks up adhesions, separates adhered fibers, and realigns scar tissue by addressing restrictions BETWEEN fibers and fascial layers.\\n\\n✅ **Why Correct**: The perpendicular approach creates controlled microtrauma that stimulates healing and tissue remodeling. Particularly effective for tendinitis, chronic tension, and scar tissue. The 90-degree angle is what distinguishes cross-fiber friction."
    },
    160: {
        "old": "The fibula is the smaller, lateral bone of the lower leg (the tibia is the larger, medial bone that bears weight). The fibula's head (proximal end) is located just below the knee on the lateral side of the leg. The common peroneal nerve wraps around the fibular head, making this an endangerment site - direct pressure here can compress the nerve, causing pain, numbness, or foot drop. This anatomical relationship makes the fibular head a critical area to avoid during massage. Therapists must use caution when working near the lateral knee to prevent nerve damage.",
        "new": "🎯 **Key Concept**: The **common peroneal nerve** wraps around the fibular head (below the knee on lateral leg), making it an **endangerment site** - direct pressure can cause pain, numbness, or foot drop.\\n\\n💡 **Memory Tip**: FIB-ula Head = FIB to your leg! Don't press the fibular head or the peroneal nerve will make your foot DROP (foot drop from nerve damage)!\\n\\n⚠️ **Exam Alert**: Fibula = smaller, lateral lower leg bone. Tibia = larger, medial weight-bearing bone. The fibular HEAD is the danger zone.\\n\\n✅ **Why Correct**: This anatomical relationship (nerve wrapping around bone) makes the fibular head critical to avoid during massage. Use caution near lateral knee to prevent nerve compression and damage."
    },
}

# Process each conversion
for question_id, replacement in conversions.items():
    old_text = replacement["old"]
    new_text = replacement["new"]

    # Escape special characters for regex
    old_escaped = re.escape(old_text)

    # Find and replace
    if old_text in content:
        content = content.replace(old_text, new_text)
        print(f"[OK] Converted question {question_id}")
    else:
        print(f"[SKIP] Could not find question {question_id} - text may have already been modified")

# Write back
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print("\\nConversion complete! Questions 145-160 updated.")
