#!/usr/bin/env python3
"""Convert questions 64-72 and remaining 49-50"""
import sys

with open(r'C:\git\nysmassageexam.com\data\questions.ts', 'r', encoding='utf-8') as f:
    content = f.read()

conversions = []

# Q64: Gracilis Exercise
old = """The gracilis muscle is a long, thin muscle of the inner thigh that performs hip adduction (bringing legs toward midline) and assists with knee flexion. It originates from the pubic bone and inserts below the knee on the medial tibia. To strengthen the gracilis specifically, exercises must target adduction movement. Squeezing a pillow between the knees directly targets this muscle's primary function - adducting the thigh. This exercise isolates the gracilis and other adductor muscles while being safe for injury recovery. The resistance can be controlled, and the movement pattern matches the muscle's anatomical function perfectly."""
new = """🎯 **Key Concept**: The gracilis is a long, thin muscle of the inner thigh that performs hip adduction (bringing legs toward midline). It originates from the pubic bone and inserts below the knee on the medial tibia.\\n\\n💡 **Memory Tip**: GRACILIS = GRACEFUL SQUEEZE - The gracilis muscle helps you gracefully squeeze your legs together, like squeezing a pillow between your knees!\\n\\n⚠️ **Exam Alert**: Generic weight training and running don't specifically target adduction. Only squeezing exercises directly isolate the gracilis muscle's primary function!\\n\\n✅ **Why Correct**: Squeezing a pillow between the knees directly targets the gracilis's primary function - adducting the thigh. The resistance can be controlled, and the movement pattern matches the muscle's anatomical function perfectly for injury recovery."""
if old in content:
    content = content.replace(old, new)
    conversions.append(64)

# Q65: Deep Massage and Scar Tissue
old = """Deep massage during healing breaks down excessive scar tissue formation through mechanical disruption of collagen fibers. When tissues heal, collagen forms in random, disorganized patterns creating restrictions and adhesions. Deep massage applies controlled stress that remodels this scar tissue, promoting more organized collagen alignment. The mechanical pressure breaks cross-links between collagen fibers, increases circulation to bring nutrients and remove waste, and stimulates fibroblasts to produce healthier tissue architecture. This doesn't reverse healing but optimizes it by preventing excessive scarring and maintaining tissue mobility. Timing is crucial - too early can disrupt healing, but at appropriate stages, deep work eliminates problematic scar tissue formation."""
new = """🎯 **Key Concept**: Deep massage breaks down excessive scar tissue through mechanical disruption of collagen fibers. When tissues heal, collagen forms in random, disorganized patterns creating restrictions and adhesions.\\n\\n💡 **Memory Tip**: DEEP massage DELETES scar tissue - like using a heavy eraser to remove unwanted marks and smooth the surface!\\n\\n⚠️ **Exam Alert**: Deep massage doesn't reverse healing or just generally aid it - it SPECIFICALLY eliminates excessive scar tissue. Timing is crucial - too early can disrupt healing!\\n\\n✅ **Why Correct**: Deep massage applies controlled stress that remodels scar tissue, promoting more organized collagen alignment. The mechanical pressure breaks cross-links between collagen fibers, increases circulation, and stimulates fibroblasts to produce healthier tissue architecture."""
if old in content:
    content = content.replace(old, new)
    conversions.append(65)

# Q66: Linea Alba
old = """The Linea Alba is a fibrous structure running vertically down the center of the anterior abdominal wall from the xiphoid process to the pubic symphysis. It's formed by the intersection and fusion of aponeuroses from the rectus abdominis, external oblique, internal oblique, and transversus abdominis muscles. The name means 'white line' in Latin, referring to its pale, tendinous appearance due to its fibrous composition and poor blood supply. This structure provides crucial core stability and serves as an attachment point for abdominal muscles. It's clinically significant as a surgical landmark and can be affected by diastasis recti (separation) during pregnancy or abdominal distension."""
new = """🎯 **Key Concept**: The Linea Alba is a fibrous structure running vertically down the center of the anterior abdominal wall from the xiphoid process to the pubic symphysis. It's formed by the fusion of aponeuroses from abdominal muscles.\\n\\n💡 **Memory Tip**: LINEA ALBA = WHITE LINE down your BELLY - Picture a white line running down the middle of your ABdomen, like a zipper on your stomach!\\n\\n⚠️ **Exam Alert**: NOT in the spine, NOT in cell membranes - it's ONLY in the abdomen! The name means 'white line' in Latin, referring to its pale, tendinous appearance.\\n\\n✅ **Why Correct**: This structure provides crucial core stability and serves as an attachment point for abdominal muscles. It's clinically significant as a surgical landmark and can be affected by diastasis recti during pregnancy."""
if old in content:
    content = content.replace(old, new)
    conversions.append(66)

# Q67: Oxygenated Blood
old = """The cardiovascular system follows a specific oxygenation pattern. The left side of the heart (left atrium and left ventricle) contains oxygenated blood that returns from the lungs via pulmonary veins. The left ventricle specifically pumps this oxygen-rich blood through the aorta to supply the entire body. The right side handles deoxygenated blood returning from body tissues. Capillaries are exchange sites where oxygen transfers from blood to tissues, so they contain both oxygenated and deoxygenated blood depending on location. Understanding this circulation pattern is crucial for comprehending how massage affects blood flow and tissue oxygenation."""
new = """🎯 **Key Concept**: The left side of the heart (left atrium and left ventricle) contains oxygenated blood that returns from the lungs via pulmonary veins. The left ventricle specifically pumps this oxygen-rich blood through the aorta to supply the entire body.\\n\\n💡 **Memory Tip**: LEFT = LIFE! The left ventricle pumps oxygenated blood to give LIFE to the body. Remember: Left = Life-giving oxygen!\\n\\n⚠️ **Exam Alert**: Right ventricle = deoxygenated blood (to lungs). Capillaries = BOTH types depending on location. Only left side = purely oxygenated!\\n\\n✅ **Why Correct**: The right side handles deoxygenated blood returning from body tissues. Understanding this circulation pattern is crucial for comprehending how massage affects blood flow and tissue oxygenation."""
if old in content:
    content = content.replace(old, new)
    conversions.append(67)

# Q68: Effleurage for Warming
old = """Effleurage consists of long, gliding strokes that gradually warm tissues through gentle friction and increased circulation. This Swedish massage technique uses broad hand contact and smooth, flowing movements that stimulate blood flow without aggressive pressure. The warming effect prepares tissues by increasing local circulation, raising tissue temperature, and relaxing muscle fibers. This makes subsequent deeper work more effective and comfortable. Effleurage also helps assess tissue condition and allows the client's nervous system to adapt to touch. Always begin massage sessions with effleurage to establish therapeutic contact and prepare tissues systematically."""
new = """🎯 **Key Concept**: Effleurage consists of long, gliding strokes that gradually warm tissues through gentle friction and increased circulation. This Swedish massage technique uses broad hand contact and smooth, flowing movements.\\n\\n💡 **Memory Tip**: EFFLEURAGE = ENTRANCE! It's your gentle entrance into the massage, like slowly entering a warm bath. Effleurage flows like a gentle stream to warm and prepare!\\n\\n⚠️ **Exam Alert**: Tapotement = percussion/stimulation (NOT warming). Petrissage = kneading (requires tissues ALREADY warmed). Only effleurage is for initial warming!\\n\\n✅ **Why Correct**: The warming effect prepares tissues by increasing local circulation, raising tissue temperature, and relaxing muscle fibers. This makes subsequent deeper work more effective and comfortable. Always begin massage sessions with effleurage."""
if old in content:
    content = content.replace(old, new)
    conversions.append(68)

# Q69: Sebum
old = """Sebum is an oily secretion produced by sebaceous glands, which are accessory structures of the integumentary system (skin, hair, nails, and associated glands). These microscopic glands are located throughout the skin, typically connected to hair follicles. Sebum contains lipids, fatty acids, and cellular debris that create a protective barrier on the skin surface. It prevents water loss, maintains skin flexibility, and provides antimicrobial protection. Understanding sebaceous gland function helps massage therapists recognize normal skin conditions versus pathological changes, and explains why certain skin types respond differently to oils and lotions during treatment."""
new = """🎯 **Key Concept**: Sebum is an oily secretion produced by sebaceous glands, which are accessory structures of the integumentary system (skin, hair, nails, and associated glands). These glands are typically connected to hair follicles.\\n\\n💡 **Memory Tip**: SEBUM = SKIN'S SUPREME SHIELD! Sebaceous glands in your skin make Sebum to keep skin Smooth and Soft. Skin = Sebum!\\n\\n⚠️ **Exam Alert**: NOT reproductive (that's hormones/gametes), NOT digestive (that's enzymes/bile). Sebum = integumentary system ONLY!\\n\\n✅ **Why Correct**: Sebum contains lipids, fatty acids, and cellular debris that create a protective barrier on the skin surface. It prevents water loss, maintains skin flexibility, and provides antimicrobial protection."""
if old in content:
    content = content.replace(old, new)
    conversions.append(69)

# Q70: Universal Precautions
old = """Universal precautions represent a comprehensive infection control system treating all human blood and bodily fluids as potentially infectious. This includes proper hand hygiene, barrier protection (gloves), safe disposal of contaminated materials, surface disinfection, and appropriate wound care protocols. These precautions protect against bloodborne pathogens like HIV, Hepatitis B and C, and other infectious diseases. While hand washing is crucial, universal precautions encompass a broader safety framework including when to use gloves, how to handle linens, equipment sterilization, and emergency procedures. Failure to follow complete universal precautions creates the greatest overall risk exposure for massage therapists and clients."""
new = """🎯 **Key Concept**: Universal precautions represent a comprehensive infection control system treating all human blood and bodily fluids as potentially infectious. This includes hand hygiene, barrier protection (gloves), safe disposal, surface disinfection, and wound care protocols.\\n\\n💡 **Memory Tip**: UNIVERSAL = UMBRELLA! Universal precautions are like a protective umbrella covering ALL potential risks - blood, bodily fluids, and unknown infections. One umbrella protects from all weather!\\n\\n⚠️ **Exam Alert**: Hand washing alone is NOT enough! Universal precautions include gloves, proper disposal, equipment sterilization, and emergency procedures. Greatest risk = not following the COMPLETE system!\\n\\n✅ **Why Correct**: These precautions protect against bloodborne pathogens like HIV, Hepatitis B and C, and other infectious diseases. Failure to follow complete universal precautions creates the greatest overall risk exposure for massage therapists and clients."""
if old in content:
    content = content.replace(old, new)
    conversions.append(70)

# Q71: ROM Evaluation
old = """Active range of motion (AROM) evaluation requires the client to move the joint independently using their own muscular effort. This assessment reveals the true functional capacity of the joint, including muscle strength, coordination, pain limitations, and actual movement restrictions. AROM testing shows what the client can realistically achieve in daily activities. It identifies both joint restrictions and muscular weaknesses simultaneously. Passive ROM (therapist moves the joint) only tests joint mobility without muscle function, while resisted movement tests strength rather than range. For comprehensive evaluation, start with AROM to understand functional limitations, then use passive ROM to differentiate between muscle and joint restrictions."""
new = """🎯 **Key Concept**: Active range of motion (AROM) evaluation requires the client to move the joint independently using their own muscular effort. This assessment reveals the true functional capacity including muscle strength, coordination, pain limitations, and actual movement restrictions.\\n\\n💡 **Memory Tip**: ACTIVE = AUTHENTIC! For true ROM evaluation, the client must do it themselves - that's the AUTHENTIC movement pattern. Active Assessment = Accurate Answer!\\n\\n⚠️ **Exam Alert**: Passive ROM = only joint mobility (therapist moves limb, no muscle function tested). Resisted = tests strength, NOT range. Only active ROM evaluates functional movement capacity!\\n\\n✅ **Why Correct**: AROM testing shows what the client can realistically achieve in daily activities. It identifies both joint restrictions and muscular weaknesses simultaneously, giving the most complete assessment picture."""
if old in content:
    content = content.replace(old, new)
    conversions.append(71)

# Q72: Professional Behavior
old = """Professional massage therapy standards focus on client safety, dignity, and therapeutic boundaries. Communication with clients during treatment is not only acceptable but often necessary for checking pressure, comfort levels, and maintaining therapeutic rapport. However, proper draping maintains client modesty and comfort, while name identification ensures accountability and professionalism. Unprofessional behaviors typically involve boundary violations, inadequate safety measures, or actions that compromise client dignity. Effective communication enhances the therapeutic relationship and treatment outcomes."""
new = """🎯 **Key Concept**: Professional massage therapy standards focus on client safety, dignity, and therapeutic boundaries. Communication with clients during treatment is not only acceptable but often NECESSARY for checking pressure, comfort levels, and maintaining therapeutic rapport.\\n\\n💡 **Memory Tip**: TCD - Talk is Cool, Draping matters! Remember: Talking = Communication (professional), but Covering properly and IDentification are essential for professionalism.\\n\\n⚠️ **Exam Alert**: NOT wearing a nametag = unprofessional (reduces accountability). Poor draping = unprofessional (violates boundaries). Talking to client = PROFESSIONAL and therapeutic!\\n\\n✅ **Why Correct**: Effective communication enhances the therapeutic relationship and treatment outcomes. Unprofessional behaviors typically involve boundary violations, inadequate safety measures, or actions that compromise client dignity."""
if old in content:
    content = content.replace(old, new)
    conversions.append(72)

with open(r'C:\git\nysmassageexam.com\data\questions.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Converted: {sorted(conversions)}")
print(f"Total: {len(conversions)}")
