#!/usr/bin/env python3
"""
Final conversion script for questions 124-144 to markdown format
"""

with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'r', encoding='utf-8') as f:
    content = f.read()

# All conversions for questions 124-144
conversions = [
    # Q124
    ("Arterial blood flow follows a proximal to distal pattern in the upper extremity. The subclavian artery originates from the aortic arch (left) or brachiocephalic trunk (right), then becomes the axillary artery as it passes under the clavicle into the armpit region. The axillary artery continues as the brachial artery in the upper arm. This sequence is essential for massage therapists to understand circulation patterns and pressure point locations during treatment.",
     "🎯 **Key Concept**: Arterial blood flow follows proximal-to-distal: **Subclavian → Axillary → Brachial** (SAB = 'SUBWAY' route from shoulder to elbow).\\n\\n💡 **Memory Tip**: SAB - 'SUBWAY' route! Blood takes the subway from shoulder to elbow: Subclavian → Axillary → Brachial.\\n\\n⚠️ **Exam Alert**: Don't reverse the sequence! Always proximal to distal. Subclavian (near chest) → Axillary (armpit) → Brachial (upper arm).\\n\\n✅ **Why Correct**: Subclavian originates from aortic arch, passes under clavicle to become axillary, then continues as brachial. Essential for understanding circulation patterns and pressure points."),

    # Q125
    ("The ulnar nerve innervates the interosseous muscles of the hand, specifically the dorsal and palmar interossei, which are responsible for finger abduction (spreading fingers apart) and adduction (bringing them together). Ulnar nerve damage typically affects the pinky and ring finger most severely, causing difficulty with fine motor tasks requiring finger spreading. This creates the characteristic 'claw hand' deformity. The ulnar nerve also controls the hypothenar muscles and contributes to grip strength through the deep finger flexors.",
     "🎯 **Key Concept**: The **ulnar nerve** innervates interosseous muscles responsible for **finger abduction (spreading)** and adduction. Damage causes 'claw hand'.\\n\\n💡 **Memory Tip**: Ulnar nerve = Finger SPREADING! Think 'U for Ulnar, U spread your fingers apart like the letter U!' Pinky and ring spread wide.\\n\\n⚠️ **Exam Alert**: Not thumb opposition (median nerve/thenar muscles) or wrist extension (radial nerve/extensors). Ulnar = finger SPREADING!\\n\\n✅ **Why Correct**: Controls interossei (dorsal/palmar) for spreading/bringing fingers together. Affects pinky/ring most. Also controls hypothenar muscles and deep finger flexors for grip."),

    # Q126
    ("The palmaris longus is one of the superficial flexor muscles of the anterior forearm compartment that produces wrist flexion (bending the hand toward the palm side). It originates from the medial epicondyle of the humerus and inserts into the palmar aponeurosis. Other wrist flexors include flexor carpi radialis and flexor carpi ulnaris. Note: about 14% of people are born without the palmaris longus muscle. These muscles are commonly tight in people who do repetitive hand/wrist activities and benefit from massage therapy.",
     "🎯 **Key Concept**: **Palmaris longus** is a superficial forearm flexor that produces **wrist flexion** (bending hand toward palm). 14% of people lack it!\\n\\n💡 **Memory Tip**: PALM-aris longus flexes your PALM toward you - it's in the name! Your palm bends toward forearm like catching something.\\n\\n⚠️ **Exam Alert**: Not extensor carpi radialis brevis (extends wrist, opposite action) or pronator quadratus (rotates forearm, no flexion). Palmaris = wrist FLEXION!\\n\\n✅ **Why Correct**: Originates medial epicondyle, inserts palmar aponeurosis. Other flexors: flexor carpi radialis/ulnaris. Commonly tight from repetitive hand/wrist activities - benefits from massage."),

    # Q127
    ("The circulatory system forms a continuous loop where arteries carry oxygenated blood away from the heart, and veins return deoxygenated blood back to the heart. The crucial connection point is the capillaries - tiny, thin-walled vessels where gas and nutrient exchange occurs. Arteries branch into smaller arterioles, then into microscopic capillaries, which then merge into venules that become veins. This capillary bed is where the actual purpose of circulation happens - oxygen and nutrients exit the blood while carbon dioxide and waste products enter. Without capillaries, there would be no functional connection between the arterial and venous systems.",
     "🎯 **Key Concept**: Arteries and veins connect at **capillaries** - tiny, thin-walled vessels where gas/nutrient exchange occurs. The meeting point!\\n\\n💡 **Memory Tip**: CAP the meeting - Capillaries Are the Place where arteries and veins meet! Like a bottle cap connecting two parts.\\n\\n⚠️ **Exam Alert**: Not venules (collect FROM capillaries, venous only) or arterioles (deliver TO capillaries, arterial only). CAPILLARIES = the connection!\\n\\n✅ **Why Correct**: Arteries → arterioles → CAPILLARIES → venules → veins. Capillary bed is where circulation's purpose happens: O₂/nutrients out, CO₂/waste in. Without capillaries, no arterial-venous connection."),

    # Q128
    ("Tonic muscle contraction is the continuous, partial contraction of muscles that maintains posture and body position against gravity. Unlike voluntary movements, tonic contractions are involuntary and sustained at low intensity to keep us upright. This constant background muscle tension prevents us from collapsing and allows us to maintain stable positioning. Postural muscles like the erector spinae, deep neck flexors, and antigravity muscles exhibit tonic activity throughout the day. This is different from phasic contractions used for movement - tonic contractions are about stability and endurance rather than power or range of motion.",
     "🎯 **Key Concept**: **Tonic contraction** = continuous, partial muscle contraction that maintains posture against gravity. Involuntary, low-intensity, sustained.\\n\\n💡 **Memory Tip**: TONIC for POSTURE! Think 'Tonic water keeps its fizz' - tonic contraction keeps posture steady with constant low-level 'fizz'!\\n\\n⚠️ **Exam Alert**: Not isometric (static exercise), isotonic (joint movement), or eccentric (lengthening during movement). Tonic = postural stability!\\n\\n✅ **Why Correct**: Constant background tension prevents collapse. Postural muscles (erector spinae, deep neck flexors, antigravity muscles) show tonic activity all day. About stability/endurance, not power/movement."),

    # Q129
    ("Fast-twitch (Type II) muscle fibers are designed for powerful, explosive movements but fatigue quickly. The quadriceps, being large locomotor muscles responsible for knee extension, jumping, and sprinting, contain a high percentage of fast-twitch fibers to generate maximum force rapidly. In contrast, postural and stabilizing muscles contain more slow-twitch fibers for endurance. The quadriceps must produce significant force against gravity during activities like standing from seated, climbing stairs, and athletic movements. This requires the rapid energy production and forceful contraction that fast-twitch fibers provide, though they sacrifice endurance for power.",
     "🎯 **Key Concept**: **Quadriceps** contain the highest proportion of **fast-twitch (Type II) fibers** for powerful, explosive movements (jumping, sprinting, knee extension).\\n\\n💡 **Memory Tip**: QUADS are QUICK! Think 'Quadriceps = Quick sprints' - built for explosive power! The bigger the muscle, the more power fibers!\\n\\n⚠️ **Exam Alert**: Not iliopsoas, erector spinae, or quadratus lumborum (postural/stabilizers with slow-twitch endurance fibers). Quads = power, not endurance!\\n\\n✅ **Why Correct**: Large locomotor muscles needing max force rapidly. Activities: standing from seated, stairs, athletics. Fast-twitch provides rapid energy/forceful contraction but sacrifices endurance for power."),

    # Q130
    ("Hemiplegia affects only one side of the body, typically following stroke or brain injury. When someone has left hemiplegia, only the left side is paralyzed or severely weakened. The right side maintains normal muscle tone and function, which actually causes the waddling gait pattern as the person compensates for the non-functional left side. The normal right side must work harder to support body weight and movement, creating the characteristic gait abnormality. Understanding this compensation pattern is crucial for massage therapists working with stroke survivors - the 'normal' side often becomes overworked and tight from compensation.",
     "🎯 **Key Concept**: In **left hemiplegia**, only left side is paralyzed. The **right side maintains normal muscle tone** - causes waddling gait from compensation.\\n\\n💡 **Memory Tip**: HEMI means HALF! If LEFT side is paralyzed (hemiplegic), RIGHT side must be NORMAL to compensate! 'Right side picks up the slack.'\\n\\n⚠️ **Exam Alert**: Not spastic, spasm, or flaccid (those describe the affected LEFT side). Right side in left hemiplegia = NORMAL tone!\\n\\n✅ **Why Correct**: Hemiplegia affects one side only. Normal side works harder, creates compensation patterns. Critical for massage therapists: 'normal' side becomes overworked and tight from compensating."),

    # Q131
    ("Multiple sclerosis (MS) is an autoimmune disease where the body's immune system attacks myelin - the fatty insulation around nerve fibers in the central nervous system. This demyelination creates sclerotic plaques (hardened scar tissue) that disrupt nerve signal transmission. The 'multiple' refers to many locations affected throughout the brain and spinal cord. White matter appears white due to its high myelin content, so MS specifically damages white matter. This results in varied neurological symptoms depending on lesion location - vision problems, weakness, numbness, coordination issues. Understanding MS helps massage therapists recognize contraindications and work appropriately with affected clients during remission periods.",
     "🎯 **Key Concept**: **Multiple sclerosis (MS)** = autoimmune disease attacking **myelin** (fatty nerve insulation), creating sclerotic plaques in CNS white matter.\\n\\n💡 **Memory Tip**: MS = Myelin Sclerosis! Think 'Multiple Scars' - multiple sclerotic (hardened) plaques replace healthy myelin. 'S' in MS = Sclerosis (scarring)!\\n\\n⚠️ **Exam Alert**: Not muscular dystrophy (muscle fibers), Parkinson's (dopamine/gray matter), or stroke (vascular). MS = WHITE matter demyelination!\\n\\n✅ **Why Correct**: Autoimmune attack on myelin disrupts nerve signals. Multiple brain/spinal cord locations. Symptoms: vision problems, weakness, numbness, coordination issues. Massage during remission only."),

    # Q132
    ("Parkinson's Disease is a progressive neurological disorder caused by dopamine deficiency in the substantia nigra. The hallmark motor symptoms include fine tremors (typically 4-6 Hz pill-rolling tremor at rest), muscle rigidity (increased resistance to passive movement), bradykinesia (slowness of movement), and postural instability. The tremors are characteristically fine and rhythmic, often described as 'pill-rolling' between thumb and fingers. Rigidity occurs due to increased muscle tone affecting both flexor and extensor muscles simultaneously, creating a 'cogwheel' or 'lead pipe' resistance during examination. This differs from flaccidity (decreased muscle tone) seen in lower motor neuron diseases.",
     "🎯 **Key Concept**: Parkinson's Disease = **fine tremors** (4-6 Hz pill-rolling at rest) + **muscle rigidity** (increased resistance). NOT flaccidity!\\n\\n💡 **Memory Tip**: Parkinson's has FINE dining with RIGID rules - Fine tremors with Rigid muscles, not floppy flaccid ones!\\n\\n⚠️ **Exam Alert**: Not fine + flaccidity, or coarse tremors. Parkinson's = FINE tremors + RIGIDITY (cogwheel/lead pipe resistance).\\n\\n✅ **Why Correct**: Dopamine deficiency causes fine pill-rolling tremor, rigidity (both flexor/extensor), bradykinesia, postural instability. Rigidity ≠ flaccidity (opposite: decreased tone)."),

    # Q133
    ("Parkinson's disease is caused by the progressive loss of dopamine-producing neurons in the substantia nigra, a region of the midbrain. Dopamine is a crucial neurotransmitter responsible for smooth, coordinated movement and motor control. When 60-80% of these dopaminergic neurons are lost, the characteristic symptoms of Parkinson's emerge. This neurotransmitter deficiency disrupts the normal balance in the basal ganglia circuitry, leading to the motor symptoms of tremor, rigidity, bradykinesia, and postural instability. The disease is primarily neurochemical in nature, distinguishing it from muscular disorders that affect the muscle tissue itself rather than the nervous system's chemical communication.",
     "🎯 **Key Concept**: **Parkinson's disease** = progressive loss of **dopamine**-producing neurons in substantia nigra (midbrain). 60-80% loss causes symptoms.\\n\\n💡 **Memory Tip**: PARK your DOPAmine - Parkinson's PARKs because there's no DOPAmine fuel left in the brain tank!\\n\\n⚠️ **Exam Alert**: Not muscular dystrophy (affects muscle proteins, not neurotransmitters). Parkinson's = BRAIN CHEMISTRY (dopamine), not muscle disease!\\n\\n✅ **Why Correct**: Dopamine = crucial neurotransmitter for smooth movement. Deficiency disrupts basal ganglia circuitry → tremor, rigidity, bradykinesia, postural instability. Neurochemical vs. muscular."),

    # Q134
    ("Intervertebral foramina are lateral openings formed between adjacent vertebrae, created by the superior and inferior vertebral notches. These foramina serve as exit points for spinal nerves as they branch off from the spinal cord. Each thoracic level has paired spinal nerves (left and right) that pass through these openings, carrying both motor and sensory fibers. The spinal nerves then divide into dorsal and ventral rami to innervate specific body regions. This anatomical arrangement is consistent throughout the spine - cervical, thoracic, lumbar, and sacral regions all have spinal nerves exiting through intervertebral foramina. Understanding this pathway is crucial for recognizing nerve compression syndromes and radiculopathies.",
     "🎯 **Key Concept**: **Spinal nerves** exit through intervertebral foramina (lateral openings between vertebrae). Each thoracic level has paired nerves (L+R).\\n\\n💡 **Memory Tip**: NERVES need NARROW passages - Spinal NERVES squeeze through Narrow intervertebral foramina like cars through a tunnel!\\n\\n⚠️ **Exam Alert**: Not vertebral arteries (transverse foramina in cervical) or spinal cord (central vertebral canal). Intervertebral foramina = SPINAL NERVES!\\n\\n✅ **Why Correct**: Lateral openings formed by superior/inferior vertebral notches. Spinal nerves exit here carrying motor/sensory fibers, then divide into dorsal/ventral rami. Crucial for understanding nerve compression/radiculopathies."),

    # Q135
    ("The human spinal cord gives rise to 31 pairs of spinal nerves, distributed as follows: 8 cervical pairs (C1-C8), 12 thoracic pairs (T1-T12), 5 lumbar pairs (L1-L5), 5 sacral pairs (S1-S5), and 1 coccygeal pair (Co1). Note that there are 8 cervical nerve pairs despite only 7 cervical vertebrae - C8 exits between C7 and T1 vertebrae. Each pair consists of left and right nerves, making 62 individual spinal nerves total. These nerves carry motor, sensory, and autonomic fibers to innervate the entire body below the head. The number 31 is critical for understanding spinal anatomy, dermatome patterns, and neurological examination.",
     "🎯 **Key Concept**: **31 pairs** of spinal nerves: 8 cervical + 12 thoracic + 5 lumbar + 5 sacral + 1 coccygeal = 31 pairs (62 individual nerves).\\n\\n💡 **Memory Tip**: Celebrate 31! C8-T12-L5-S5-Co1 = 8+12+5+5+1 = 31 pairs (like 31 flavors at the spine shop!)\\n\\n⚠️ **Exam Alert**: Not 12 (thoracic pairs only), 24 (incomplete), or 62 (individual nerves, not pairs). Answer = 31 PAIRS!\\n\\n✅ **Why Correct**: Note: 8 cervical pairs despite only 7 cervical vertebrae (C8 exits C7-T1). Each pair = left + right. Carry motor/sensory/autonomic fibers. Critical for spinal anatomy/dermatomes."),

    # Q136
    ("The carpal bones are arranged in two rows: proximal (closer to forearm) and distal (closer to fingers). The proximal row contains four bones from lateral to medial: Scaphoid, Lunate, Triquetrum, and Pisiform. The lunate gets its name from its crescent or half-moon shape and sits in the middle of the proximal row. It articulates with the radius above and the capitate and hamate below. The distal row contains: Trapezium, Trapezoid, Capitate, and Hamate (remembered as 'That These Can Handle'). Understanding carpal anatomy is essential for massage therapists when working with wrist conditions, carpal tunnel syndrome, and hand/forearm techniques.",
     "🎯 **Key Concept**: **Lunate** is in the **proximal row** of carpals (closer to forearm). Proximal row: Scaphoid, Lunate, Triquetrum, Pisiform.\\n\\n💡 **Memory Tip**: Some Lovers Try Positions (proximal): Scaphoid, Lunate, Triquetrum, Pisiform. LUNATE = crescent moon in the proximal sky!\\n\\n⚠️ **Exam Alert**: Not hamate, trapezoid, or capitate (all in DISTAL row). Proximal vs. distal is key! Lunate = PROXIMAL!\\n\\n✅ **Why Correct**: Lunate = crescent/half-moon shape, middle of proximal row. Articulates with radius above, capitate/hamate below. Distal row: Trapezium, Trapezoid, Capitate, Hamate."),

    # Q137
    ("The diaphysis is the central shaft of long bones, forming the main cylindrical portion between the two ends. It consists primarily of compact bone tissue surrounding the medullary cavity, which contains bone marrow. The diaphysis provides structural support and strength to withstand mechanical stress. The thick compact bone walls (cortical bone) make it the strongest part of long bones. This region is where most fractures occur due to trauma, making it clinically significant for massage therapists to understand when working around healed fracture sites.",
     "🎯 **Key Concept**: **Diaphysis** = central shaft of long bones. Main cylindrical portion with compact bone surrounding medullary cavity (marrow).\\n\\n💡 **Memory Tip**: DIA-physis = DIAmeter of the shaft! Think main 'dial' or central part giving bone its length and strength.\\n\\n⚠️ **Exam Alert**: Not epiphysis (rounded bone ends) or medullary cavity (hollow interior space with marrow). Diaphysis = the SHAFT structure!\\n\\n✅ **Why Correct**: Provides structural support, strength for mechanical stress. Thick compact bone walls (cortical bone) = strongest part. Most fractures occur here - clinically significant for massage."),

    # Q138
    ("Foot phalanges are classified as long bones despite their small size. Bone classification is based on shape and structure, not size. Long bones have a distinct shaft (diaphysis) with expanded ends (epiphyses), which phalanges possess. They contain a medullary cavity and follow the same structural pattern as larger long bones like the femur. The 14 phalanges in each foot (great toe has 2, other toes have 3 each) provide leverage for push-off during walking and absorb impact forces. Understanding this classification helps massage therapists recognize why these small bones can be prone to stress fractures and benefit from proper foot massage techniques.",
     "🎯 **Key Concept**: Foot phalanges = **long bones** despite small size! Classification based on shape/structure (shaft + ends), NOT size.\\n\\n💡 **Memory Tip**: Phalanges are LONG and STRONG for walking along! Small but have classic long bone shape - size doesn't determine classification.\\n\\n⚠️ **Exam Alert**: Not short bones (cube-shaped like wrist/ankle), sesamoid (develop in tendons), or cuboid (specific tarsal bone). Phalanges = LONG bones!\\n\\n✅ **Why Correct**: Have distinct shaft (diaphysis) + expanded ends (epiphyses) + medullary cavity. 14 per foot (big toe 2, others 3). Provide leverage for push-off, absorb impact. Prone to stress fractures."),

    # Q139
    ("The atlas (C1 vertebra) articulates with the occipital condyles to form the atlanto-occipital joint, which allows nodding movements of the head. The occipital condyles are two smooth, oval projections on the underside of the skull that fit into corresponding facets on the atlas. This joint bears the entire weight of the head and is crucial for head positioning. The atlas has no vertebral body, creating a ring-like structure that accommodates the skull's weight distribution. This joint is often involved in tension headaches and neck stiffness, making it a key area for therapeutic massage intervention targeting suboccipital muscles.",
     "🎯 **Key Concept**: The **atlas (C1)** articulates with occipital condyles, forming the atlanto-occipital joint for head nodding. Bears entire head weight!\\n\\n💡 **Memory Tip**: ATLAS holds up the world (your head)! Like Greek god Atlas carried the globe, Atlas vertebra carries your skull via occipital condyles.\\n\\n⚠️ **Exam Alert**: Not axis (C2, articulates with atlas below skull), occipital protuberance (muscle attachment, not joint), or mastoid (temporal bone, no vertebral joint).\\n\\n✅ **Why Correct**: Atlas has no vertebral body, creating ring structure for skull weight. Often involved in tension headaches/neck stiffness - key for suboccipital massage intervention."),

    # Q140
    ("The Latissimus Dorsi is a large, triangular back muscle that originates from the lower spine, pelvis, and ribs, inserting at the humerus. Its primary actions include adduction, extension, and internal rotation of the arm, plus depression of the shoulder girdle. Think of it as the 'swimming muscle' - it pulls the arms down and back toward the body during freestyle stroke. The depression action occurs because the muscle fibers pull the shoulder blade and entire shoulder complex downward and inward. This is crucial for activities like pull-ups, swimming, and any overhead-to-down movements.",
     "🎯 **Key Concept**: **Latissimus Dorsi** primary action = **depression of shoulder girdle** (pulls shoulders down/back). Also: adduction, extension, internal rotation of arm.\\n\\n💡 **Memory Tip**: Lats DEPRESS you - Like a superhero cape pulling your shoulders DOWN and back! The 'Lat Cape' always pulls DOWN (depression).\\n\\n⚠️ **Exam Alert**: Not lateral rotation (infraspinatus/teres minor), flexion (anterior deltoid), or neck extension (upper traps). Lats = shoulder girdle DEPRESSION!\\n\\n✅ **Why Correct**: Large triangular back muscle. 'Swimming muscle' - pulls arms down/back during freestyle. Crucial for pull-ups, swimming, overhead-to-down movements."),

    # Q141
    ("Respiration involves multiple muscle groups working together. Primary muscles include the diaphragm and intercostals (between ribs) for inspiration. Secondary respiratory muscles include abdominals for forced expiration, pelvic floor muscles that assist with intra-abdominal pressure regulation during breathing, and various accessory muscles. Deltoids, the shoulder muscles responsible for arm elevation and rotation, have no direct role in breathing mechanics. They don't attach to ribs or contribute to thoracic cavity volume changes. Understanding respiratory muscle function is crucial for massage therapists working with clients who have breathing difficulties or postural issues affecting respiration.",
     "🎯 **Key Concept**: **Deltoids** have minimal/NO involvement in respiration. They're shoulder muscles for arm movement, don't attach to ribs or affect breathing.\\n\\n💡 **Memory Tip**: DELTOIDS Don't help you BREATHE - they're for your SLEEVES! Pelvic floor = pump, Intercostals = rib movers, Abs = exhale force.\\n\\n⚠️ **Exam Alert**: Pelvic floor (intra-abdominal pressure), intercostals (primary respiratory), abdominals (forced expiration) ALL help breathing. Only deltoids DON'T!\\n\\n✅ **Why Correct**: Primary: diaphragm + intercostals. Secondary: abs (forced expiration), pelvic floor (pressure regulation), accessory muscles. Deltoids = arm elevation/rotation only."),

    # Q142
    ("Quiet respiration (normal, resting breathing) primarily involves only two muscle groups: the diaphragm and external intercostals. The diaphragm does 75% of the work during inspiration by contracting and flattening, creating negative pressure. External intercostals assist by elevating the ribs and expanding the thoracic cavity. Scalenes, rhomboids, and SCM are accessory respiratory muscles that only activate during forced or labored breathing, exercise, or respiratory distress. This distinction is crucial for understanding normal versus pathological breathing patterns in massage therapy assessment.",
     "🎯 **Key Concept**: Quiet respiration uses only **2 muscles**: **Diaphragm** (75% of work) + **external intercostals**. Scalenes/rhomboids/SCM = forced breathing only!\\n\\n💡 **Memory Tip**: QUIET breathing needs QUIET muscles - just the 'Dynamic Duo': Diaphragm + eXternal intercostals. When breathing gets LOUD, need MORE help!\\n\\n⚠️ **Exam Alert**: Scalenes, rhomboids, SCM are ACCESSORY muscles (forced/labored breathing only). Quiet respiration = diaphragm + external intercostals ONLY!\\n\\n✅ **Why Correct**: Diaphragm contracts/flattens, creates negative pressure. External intercostals elevate ribs, expand thoracic cavity. Critical for understanding normal vs. pathological breathing patterns."),

    # Q143
    ("The diaphragm actively contracts only during inhalation, flattening from its dome shape and moving downward to expand the thoracic cavity. This creates negative pressure that draws air into the lungs. During quiet exhalation, the diaphragm passively relaxes and returns to its dome position through elastic recoil - no active contraction occurs. The diaphragm is the primary muscle of inspiration, responsible for about 75% of the work during normal breathing. Understanding this active vs. passive distinction helps massage therapists assess breathing patterns and identify respiratory dysfunction.",
     "🎯 **Key Concept**: Diaphragm actively contracts during **INHALATION** (flattens, moves down, creates negative pressure). Exhalation = passive relaxation (elastic recoil).\\n\\n💡 **Memory Tip**: Diaphragm DROPS DOWN during INhalation - 'IN and DOWN' go together! EXhalation = elastic recoil, no active work at rest.\\n\\n⚠️ **Exam Alert**: Not exhalation (passive relaxation, not active). Diaphragm is PRIMARY INSPIRATION muscle (75% of breathing work)!\\n\\n✅ **Why Correct**: Contracts → flattens from dome → moves downward → expands thoracic cavity → negative pressure → air drawn in. Exhalation: passive return to dome via elastic recoil."),

    # Q144
    ("The trapezius, particularly its upper fibers, is the primary muscle responsible for extending the head and neck from a flexed position. When the head drops forward (flexion), the upper trapezius contracts to lift it back up and return it to neutral or extended position. This muscle originates from the occiput and cervical/thoracic vertebrae and inserts on the clavicle and scapula, giving it excellent leverage for head extension. The trapezius is frequently overworked in people with forward head posture, making it a common target for massage therapy to address neck tension and postural issues.",
     "🎯 **Key Concept**: **Trapezius** (upper fibers) = primary muscle for **extending head/neck from flexed position**. Lifts head back up when it drops forward.\\n\\n💡 **Memory Tip**: TRAP the head from falling forward! Trapezius = 'head TRAPPER' - TRAPs and lifts head back up when it drops into flexion!\\n\\n⚠️ **Exam Alert**: Not SCM (flexes neck/rotates head) or rhomboids (scapular retractors). Trapezius = head/neck EXTENSION from flexion!\\n\\n✅ **Why Correct**: Originates occiput + cervical/thoracic vertebrae, inserts clavicle/scapula. Excellent leverage for extension. Overworked in forward head posture - common massage target for neck tension.")
]

# Apply replacements
count = 124
for old_text, new_text in conversions:
    if old_text in content:
        content = content.replace(old_text, new_text)
        print(f"[OK] Converted question {count}")
    else:
        print(f"[SKIP] Could not find question {count}")
    count += 1

# Write back
with open('C:\\git\\nysmassageexam.com\\data\\questions.ts', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"\n{'='*60}")
print("Conversion complete for questions 124-144!")
print(f"{'='*60}")
